#

In [1]:
source('/ictstr01/home/icb/bhavishya.nelakuditi/mofa_workflow/scripts/MS0_Libraries.r')

[1] "/ictstr01/home/icb/bhavishya.nelakuditi/miniconda3/envs/my_jupyter_env/lib/R/library/"

Warning message:
“package ‘ggplot2’ was built under R version 4.3.3”
Warning message:
“package ‘tibble’ was built under R version 4.3.3”
Warning message:
“package ‘purrr’ was built under R version 4.3.3”
Warning message:
“package ‘stringr’ was built under R version 4.3.3”
Warning message:
“package ‘forcats’ was built under R version 4.3.3”
Warning message:
“package ‘lubridate’ was built under R version 4.3.3”
── Attaching core tidyverse packages ──────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ lubridate 1.9.3     ✔ tibble    3.2.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Warning message:
“package ‘backports’ was built under R version 4.3.3”

Attaching package: ‘backports’


The following object is masked from ‘package:purrr’:

    %||%


Warning message:
“package ‘ggraph’ was built under R version 4.3.3”
Warning message:
“package ‘ggpubr’ was built under R version 4.3.3”
Warning message:
“package ‘corrplot’ was built under R version 4.3.3”
corrplot 0.94 loaded


Attaching package: ‘data.table’


The following objects are masked from ‘package:lubridate’:

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year


The following objects are masked from ‘package:dplyr’:

    between, first, last


The following object is masked from ‘package:purrr’:

    transpose


Warning message:
“package ‘reshape2’ was built under R version 4.3.3”

Attaching package: ‘reshape2’


The following objects are masked from ‘package:data.table’:

    dcast, melt


The following object is masked from ‘package:tidyr’:

    smiths


Warning message:
“package ‘gridExtra’ was built under R version 4.3.3”

Attaching package: ‘gridExtra’


The following object is masked from ‘package:dplyr’:

    combine


Warning message:
“package ‘scales’ was built under R version 4.3.3”

Attaching package: ‘scales’


The following object is masked from ‘package:purrr’:

    discard


The following object is masked from ‘package:readr’:

    col_factor



Attaching package: ‘reticulate’


The following object is masked from ‘package:backports’:

    import



Attaching package: ‘MOFA2’


The following object is masked from ‘package:stats’:

    predict

In [2]:
source('/ictstr01/home/icb/bhavishya.nelakuditi/mofa_workflow/scripts/utils_vignettes.R')

In [3]:
library(caret)
library(glmnet)
library(ggplot2)

Loading required package: lattice


Attaching package: ‘caret’


The following object is masked from ‘package:purrr’:

    lift


Loading required package: Matrix


Attaching package: ‘Matrix’


The following objects are masked from ‘package:tidyr’:

    expand, pack, unpack


Loaded glmnet 4.1-8

In [1]:
uke_bulk_seq = read.csv("bulk_seq_uke_common_genes.csv")

In [2]:
head(uke_bulk_seq)

  X sample_id  A2M        A2ML1       A4GALT     AAAS       AACS
1 1 LCLC100001  0.5997504 -0.02958105  1.8067808 -0.6970965  0.1921931
2 2 LCLC100002 -0.6721709 -0.02958105 -0.3222069  0.9576292  0.6325305
3 3 LCLC100003  0.4524649 -0.02958105  0.6876994 -1.1461798  0.6629312
4 4 LCLC100004  0.5303487 -0.02958105 -0.3222069  0.5035856 -0.6160577
5 5 LCLC100005 -0.6721709 -0.02958105 -0.3222069 -0.3535220 -0.6160577
6 6 LCLC100006  1.3409367 -0.02958105  1.8195347  1.7193771 -0.6160577
  AAGAB      AAK1        AAMDC      ⋯ ZUP1        ZW10        ZWILCH
1  0.1546599  1.06446307  0.1446899 ⋯  2.26359850  0.95762923  1.2743016
2 -1.1135164 -1.87375923 -0.9654557 ⋯  0.07153808 -0.10990123  1.4555175
3  0.5879902 -0.05548483  1.2052108 ⋯  0.28221615 -0.09503488 -0.1173433
4  0.2022457 -0.25029415 -0.8751096 ⋯  0.86431666  0.00369710 -1.0199167
5  0.9812888  1.38139251  0.8152208 ⋯ -1.32892068 -0.97532273  0.6783626
6  1.2052108  0.68769942  1.0366443 ⋯ -0.51059285 -0.97532273  2.0024992
  ZWINT      ZXDA       ZXDB       ZXDC       ZYG11B      ZYX
1  1.0472479  1.3687052  0.4172446 -0.4551970 -0.08018952 -1.1227267
2 -0.4634137 -0.3522105 -0.4868678 -0.6175483 -0.56470948  0.9595803
3 -0.4634137 -0.3522105  0.8430269  0.6265207  2.12686067 -0.5531837
4 -0.4634137  2.2967637 -0.4868678  0.4716619  0.94407222 -0.2135793
5  0.8896609  1.2001309 -0.4868678  0.3745911 -0.96545569 -1.4626635
6  0.9933270 -0.3522105 -0.4868678 -1.7302862  1.03664427 -0.2299992
  ZZEF1
1  0.977307558
2 -0.145935296
3  0.662931180
4  0.681468296
5 -0.237598230
6  0.001232364

In [3]:
rownames(uke_bulk_seq) = uke_bulk_seq$sample_id

In [4]:
uke_bulk_seq <- subset(uke_bulk_seq, select = -c(X,sample_id))

In [5]:
head(uke_bulk_seq)

           A2M        A2ML1       A4GALT     AAAS       AACS       AAGAB
LCLC100001  0.5997504 -0.02958105  1.8067808 -0.6970965  0.1921931  0.1546599
LCLC100002 -0.6721709 -0.02958105 -0.3222069  0.9576292  0.6325305 -1.1135164
LCLC100003  0.4524649 -0.02958105  0.6876994 -1.1461798  0.6629312  0.5879902
LCLC100004  0.5303487 -0.02958105 -0.3222069  0.5035856 -0.6160577  0.2022457
LCLC100005 -0.6721709 -0.02958105 -0.3222069 -0.3535220 -0.6160577  0.9812888
LCLC100006  1.3409367 -0.02958105  1.8195347  1.7193771 -0.6160577  1.2052108
           AAK1        AAMDC      AAMP        AANAT       ⋯ ZUP1
LCLC100001  1.06446307  0.1446899 -0.36930857 -0.02464978 ⋯  2.26359850
LCLC100002 -1.87375923 -0.9654557 -0.08637275 -0.02464978 ⋯  0.07153808
LCLC100003 -0.05548483  1.2052108 -0.46341372 -0.02464978 ⋯  0.28221615
LCLC100004 -0.25029415 -0.8751096 -1.25510808 -0.02464978 ⋯  0.86431666
LCLC100005  1.38139251  0.8152208 -0.53034867 -0.02464978 ⋯ -1.32892068
LCLC100006  0.68769942  1.0366443  0.34566186 -0.02464978 ⋯ -0.51059285
           ZW10        ZWILCH     ZWINT      ZXDA       ZXDB       ZXDC
LCLC100001  0.95762923  1.2743016  1.0472479  1.3687052  0.4172446 -0.4551970
LCLC100002 -0.10990123  1.4555175 -0.4634137 -0.3522105 -0.4868678 -0.6175483
LCLC100003 -0.09503488 -0.1173433 -0.4634137 -0.3522105  0.8430269  0.6265207
LCLC100004  0.00369710 -1.0199167 -0.4634137  2.2967637 -0.4868678  0.4716619
LCLC100005 -0.97532273  0.6783626  0.8896609  1.2001309 -0.4868678  0.3745911
LCLC100006 -0.97532273  2.0024992  0.9933270 -0.3522105 -0.4868678 -1.7302862
           ZYG11B      ZYX        ZZEF1
LCLC100001 -0.08018952 -1.1227267  0.977307558
LCLC100002 -0.56470948  0.9595803 -0.145935296
LCLC100003  2.12686067 -0.5531837  0.662931180
LCLC100004  0.94407222 -0.2135793  0.681468296
LCLC100005 -0.96545569 -1.4626635 -0.237598230
LCLC100006  1.03664427 -0.2299992  0.001232364

In [9]:
rnaRes_top_500_genes = readRDS("top_500_genes_rnaRes.rds")

In [10]:

best_model_index <- which.max(rnaRes_top_500_genes$r2Train)
best_model_index
# Extract the best model
best_model <- rnaRes_top_500_genes$modelList[[best_model_index]]
best_model
# Get the optimal lambda value for the best model
best_lambda <- rnaRes_top_500_genes$lambdaList[best_model_index]
best_lambda

[1] 16

Loading required package: Matrix

  [[ suppressing 100 column names ‘s0’, ‘s1’, ‘s2’ ... ]]

$lambda
  [1] 0.671209200 0.640701706 0.611580824 0.583783532 0.557249670 0.531921812
  [7] 0.507745145 0.484667344 0.462638466 0.441610833 0.421538939 0.402379344
 [13] 0.384090582 0.366633072 0.349969033 0.334062400 0.318878749 0.304385217
 [19] 0.290550440 0.277344474 0.264738739 0.252705955 0.241220079 0.230256254
 [25] 0.219790752 0.209800923 0.200265148 0.191162788 0.182474144 0.174180412
 [31] 0.166263644 0.158706705 0.151493240 0.144607638 0.138034998 0.131761094
 [37] 0.125772349 0.120055802 0.114599080 0.109390375 0.104418414 0.099672436
 [43] 0.095142170 0.090817811 0.086690002 0.082749807 0.078988701 0.075398543
 [49] 0.071971562 0.068700344 0.065577807 0.062597195 0.059752056 0.057036232
 [55] 0.054443848 0.051969291 0.049607206 0.047352482 0.045200239 0.043145818
 [61] 0.041184774 0.039312863 0.037526032 0.035820416 0.034192323 0.032638229
 [67] 0.031154771 0.029738739 0.028387067 0.027096831 0.025865238 0.024689623
 [73] 0.023567442 0.022496265 0.021473775 0.020497759 0.019566104 0.018676795
 [79] 0.017827906 0.017017600 0.016244124 0.015505803 0.014801040 0.014128310
 [85] 0.013486157 0.012873190 0.012288084 0.011729571 0.011196444 0.010687549
 [91] 0.010201783 0.009738096 0.009295485 0.008872991 0.008469699 0.008084739
 [97] 0.007717275 0.007366513 0.007031693 0.006712092

$cvm
  [1] 0.83329049 0.80830426 0.77639012 0.74368217 0.70868210 0.67421319
  [7] 0.64061262 0.60567697 0.57313361 0.54334823 0.51505880 0.48499215
 [13] 0.45636142 0.42903427 0.40289995 0.37910338 0.35750027 0.33784489
 [19] 0.31992356 0.30352248 0.28874920 0.27535199 0.26326347 0.25247981
 [25] 0.24236614 0.23265408 0.22356554 0.21527712 0.20778148 0.20109662
 [31] 0.19523665 0.18952681 0.18402904 0.17899304 0.17439404 0.16949310
 [37] 0.16501201 0.16092785 0.15762133 0.15448925 0.15161777 0.14894596
 [43] 0.14656033 0.14449235 0.14238077 0.14060925 0.13859646 0.13671170
 [49] 0.13464203 0.13277724 0.13115946 0.12974637 0.12849166 0.12735450
 [55] 0.12606766 0.12395699 0.12170748 0.11984407 0.11834417 0.11695453
 [61] 0.11585831 0.11460058 0.11362544 0.11280492 0.11199775 0.11130034
 [67] 0.11062803 0.11011265 0.10966210 0.10917720 0.10884687 0.10809759
 [73] 0.10722323 0.10643847 0.10576891 0.10508975 0.10417031 0.10314640
 [79] 0.10193975 0.10075540 0.09992020 0.09923488 0.09852897 0.09782774
 [85] 0.09708615 0.09636973 0.09556856 0.09490596 0.09424294 0.09367769
 [91] 0.09327837 0.09282458 0.09233651 0.09187375 0.09145146 0.09106578
 [97] 0.09056236 0.09006872 0.08967378 0.08936457

$cvsd
  [1] 0.113975093 0.117938051 0.116504227 0.113067133 0.108426804 0.103878065
  [7] 0.099636517 0.094781605 0.090260249 0.086137456 0.081936285 0.077668842
 [13] 0.073551885 0.069749690 0.065891352 0.062347371 0.059119157 0.056125567
 [19] 0.053394543 0.050961316 0.048611412 0.046421074 0.044414883 0.042660627
 [25] 0.041000632 0.039475200 0.038178646 0.036994761 0.035888515 0.034900887
 [31] 0.034010633 0.032979046 0.031748811 0.030613416 0.029669333 0.028883852
 [37] 0.028245686 0.027581883 0.026997870 0.026524130 0.026289178 0.026027253
 [43] 0.025665202 0.025291323 0.024787874 0.024244742 0.023687871 0.023192386
 [49] 0.022712572 0.022303598 0.021899190 0.021536820 0.021172501 0.020703684
 [55] 0.020214349 0.019701177 0.019254365 0.018623967 0.018028819 0.017539315
 [61] 0.017021138 0.016705859 0.016368764 0.015992198 0.015669698 0.015369122
 [67] 0.014978904 0.014518529 0.014049348 0.013660546 0.013204041 0.012654978
 [73] 0.012078019 0.011491522 0.011061698 0.010681145 0.010314809 0.009891358
 [79] 0.009576699 0.009397764 0.009274928 0.009126278 0.009000589 0.008888286
 [85] 0.008772890 0.008659718 0.008558773 0.008383211 0.008278888 0.008197288
 [91] 0.008089010 0.007960390 0.007805133 0.007644411 0.007429383 0.007169693
 [97] 0.006925637 0.006706616 0.006560509 0.006409564

$cvup
  [1] 0.94726559 0.92624231 0.89289435 0.85674930 0.81710891 0.77809126
  [7] 0.74024914 0.70045858 0.66339386 0.62948568 0.59699508 0.56266099
 [13] 0.52991330 0.49878396 0.46879130 0.44145075 0.41661942 0.39397046
 [19] 0.37331811 0.35448380 0.33736061 0.32177307 0.30767835 0.29514044
 [25] 0.28336677 0.27212928 0.26174418 0.25227188 0.24366999 0.23599750
 [31] 0.22924728 0.22250586 0.21577785 0.20960646 0.20406337 0.19837695
 [37] 0.19325769 0.18850973 0.18461920 0.18101338 0.17790695 0.17497322
 [43] 0.17222553 0.16978368 0.16716864 0.16485399 0.16228433 0.15990408
 [49] 0.15735460 0.15508084 0.15305865 0.15128319 0.14966416 0.14805818
 [55] 0.14628200 0.14365817 0.14096185 0.13846803 0.13637299 0.13449384
 [61] 0.13287945 0.13130644 0.12999421 0.12879711 0.12766744 0.12666946
 [67] 0.12560693 0.12463118 0.12371145 0.12283774 0.12205091 0.12075256
 [73] 0.11930125 0.11793000 0.11683060 0.11577089 0.11448512 0.11303776
 [79] 0.11151645 0.11015316 0.10919513 0.10836116 0.10752956 0.10671603
 [85] 0.10585904 0.10502945 0.10412733 0.10328917 0.10252183 0.10187498
 [91] 0.10136738 0.10078497 0.10014165 0.09951816 0.09888084 0.09823547
 [97] 0.09748800 0.09677534 0.09623429 0.09577413

$cvlo
  [1] 0.71931540 0.69036621 0.65988589 0.63061504 0.60025530 0.57033513
  [7] 0.54097610 0.51089536 0.48287336 0.45721077 0.43312251 0.40732330
 [13] 0.38280953 0.35928458 0.33700860 0.31675601 0.29838111 0.28171933
 [19] 0.26652902 0.25256116 0.24013779 0.22893092 0.21884859 0.20981919
 [25] 0.20136551 0.19317888 0.18538689 0.17828236 0.17189296 0.16619573
 [31] 0.16122602 0.15654777 0.15228023 0.14837962 0.14472471 0.14060925
 [37] 0.13676632 0.13334597 0.13062346 0.12796512 0.12532859 0.12291871
 [43] 0.12089513 0.11920103 0.11759289 0.11636451 0.11490859 0.11351931
 [49] 0.11192946 0.11047364 0.10926027 0.10820955 0.10731916 0.10665081
 [55] 0.10585331 0.10425582 0.10245312 0.10122010 0.10031535 0.09941521
 [61] 0.09883717 0.09789472 0.09725668 0.09681272 0.09632805 0.09593122
 [67] 0.09564913 0.09559412 0.09561275 0.09551665 0.09564282 0.09544261
 [73] 0.09514521 0.09494695 0.09470721 0.09440860 0.09385550 0.09325504
 [79] 0.09236305 0.09135763 0.09064527 0.09010860 0.08952838 0.08893946
 [85] 0.08831326 0.08771001 0.08700978 0.08652275 0.08596405 0.08548040
 [91] 0.08518936 0.08486419 0.08453138 0.08422934 0.08402208 0.08389608
 [97] 0.08363673 0.08336211 0.08311327 0.08295501

$nzero
 s0  s1  s2  s3  s4  s5  s6  s7  s8  s9 s10 s11 s12 s13 s14 s15 s16 s17 s18 s19
  0   1   2   3   4   4   4   5   5   5   6   7   7   7   7   7   7   7   7   7
s20 s21 s22 s23 s24 s25 s26 s27 s28 s29 s30 s31 s32 s33 s34 s35 s36 s37 s38 s39
  8   8   8   9  11  12  12  12  12  12  13  13  13  13  13  13  13  13  14  14
s40 s41 s42 s43 s44 s45 s46 s47 s48 s49 s50 s51 s52 s53 s54 s55 s56 s57 s58 s59
 16  16  18  18  18  19  19  19  21  21  22  23  26  26  26  27  28  28  27  28
s60 s61 s62 s63 s64 s65 s66 s67 s68 s69 s70 s71 s72 s73 s74 s75 s76 s77 s78 s79
 28  28  28  31  29  29  30  31  32  34  38  38  39  40  40  40  42  44  45  48
s80 s81 s82 s83 s84 s85 s86 s87 s88 s89 s90 s91 s92 s93 s94 s95 s96 s97 s98 s99
 49  49  49  49  52  52  53  53  52  52  52  53  54  56  57  57  61  61  60  59

$call
cv.glmnet(x = X.train, y = y.train, type.measure = "mse", nfolds = folds,
    alpha = alpha, standardize = TRUE, intercept = TRUE, family = "gaussian")

$name
                 mse
"Mean-Squared Error"

$glmnet.fit
$a0
         s0          s1          s2          s3          s4          s5
0.066434927 0.065627515 0.064559252 0.063123628 0.062295432 0.061323063
         s6          s7          s8          s9         s10         s11
0.060395482 0.059746403 0.059295909 0.058868272 0.058098198 0.057246809
        s12         s13         s14         s15         s16         s17
0.055825601 0.054462759 0.053161790 0.051919951 0.050734555 0.049603038
        s18         s19         s20         s21         s22         s23
0.048525051 0.047494022 0.046493532 0.044747543 0.043134335 0.041989773
        s24         s25         s26         s27         s28         s29
0.041261354 0.040334117 0.039443622 0.038602833 0.037799819 0.037033318
        s30         s31         s32         s33         s34         s35
0.036290274 0.035497965 0.034939065 0.034440677 0.033928006 0.033421725
        s36         s37         s38         s39         s40         s41
0.032938867 0.032477952 0.032140676 0.031942905 0.031758718 0.031654586
        s42         s43         s44         s45         s46         s47
0.031549397 0.031573161 0.031579422 0.031572416 0.031583975 0.031583272
        s48         s49         s50         s51         s52         s53
0.031618065 0.031825673 0.031947951 0.032065126 0.032090300 0.031884290
        s54         s55         s56         s57         s58         s59
0.031665368 0.031352106 0.030541755 0.029756373 0.028990951 0.028366027
        s60         s61         s62         s63         s64         s65
0.027707929 0.027062071 0.026477140 0.025665941 0.024873505 0.023975736
        s66         s67         s68         s69         s70         s71
0.023056284 0.022618371 0.021570431 0.020092224 0.018522427 0.016956053
        s72         s73         s74         s75         s76         s77
0.015142547 0.013706409 0.012378230 0.011043519 0.009758314 0.008969554
        s78         s79         s80         s81         s82         s83
0.008271719 0.007754372 0.007285814 0.006893889 0.006710474 0.006683955
        s84         s85         s86         s87         s88         s89
0.006571593 0.006291959 0.006086578 0.005864904 0.005740487 0.005515142
        s90         s91         s92         s93         s94         s95
0.005267365 0.005048215 0.004831031 0.004837082 0.004928906 0.004925248
        s96         s97         s98         s99
0.005033367 0.005024500 0.005077803 0.005009461

$beta
398 x 100 sparse Matrix of class "dgCMatrix"

AP1S2      .  .         .            .             .            .
LINC01588  .  .         .            .             .            .
PNRC1      .  .         .            .             .            .
SERPINB9   .  .         .            .             .            .
NFKBIZ     .  .         .            .             .            .
FTH1       .  .         .            .             .            .
FLNA       .  .         .            .             .            .
TMEM107    .  .         .            .             .            .
RNF19B     .  .         .            .             .            .
PFKFB3     .  .         .            .             .            .
IER3       .  .         .            .             .            .
PMAIP1     .  .         .            .             .            .
LCP2       .  .         .            .             .            .
OLR1       .  .         .            .             .            .
NFKB1      .  .         .            .             .            .
GCH1       .  .         .            .             .            .
NFKBIA     .  .         .            .             .            .
MAP3K8     .  .         .            .             .            .
GPR132     .  .         .            0.0005775304  0.015848778  0.02854289
OGFRL1     .  .         .            .             .            .
CCL3       .  .         .            .             .            .
IRAK2      .  .         .            .             .            .
CCL4L2     .  .         .            .             .            .
CDKN1A     .  .         .            .             .            .
IFNGR2     .  .         .            .             .            .
TGFB1      .  .         .            .             .            .
ECE1       .  .         .            .             .            .
PILRA      .  .         .            .             .            .
S100A10    .  .         .            .             .            .
ICAM1      .  .         .            .             .            .
RNF125     .  .         .            .             .            .
ETS2       .  .         .            .             .            .
TNFAIP8    .  .         .            .             .            .
ANXA1      .  .         .            .             .            .
UBE2D1     .  .         .            .             .            .
TNF        .  .         .            .             .            .
ITGAV      .  .         .            .             .            .
BCL2A1     .  .         .            .             .            .
TAGAP      .  .         .            .             .            .
TNFAIP2    .  .         .            .             .            .
EIF4E      .  .         .            .             .            .
PTGER4     .  .         .            .             .            .
NFE2L2     .  .         .            .             .            .
P2RY8      .  .         .            .             .            .
PELI1      .  .         .            .             .            .
IL10RA     .  .         .            .             .            .
STK10      .  .         .            .             .            .
MIR222HG   .  .         .            .             .            .
TNIP1      .  .         .            .             .            .
PLK3       .  .         .            .             .            .
BTG1       .  .         .            .             .            .
ZFP36L2    .  .         .            .             .            .
TOM1       .  .         .            .             .            .
SLC9A8     .  .         .            .             .            .
EHD1       .  .         .            .             .            .
CCNI       .  .         .            .             .            .
CD37       .  .         .            .             .            .
CHMP4B     .  .         .            .             .            .
LACTB      .  .         .            .             .            .
SH3BGRL3   .  .         .            .             .            .
PPT1       .  .         .            .             .            .
PPP2R5C    .  .         .            .             .            .
KDM6B      .  .         .            .             .            .
GNAI2      .  .         .            .             .            .
SEC11A     .  .         .            .             .            .
CCL4       .  .         .            .             .            .
LPXN       .  .         .            .             .            .
PTGS2      .  .         .            .             .            .
AHNAK      .  .         .            .             .            .
BASP1      .  .         .            .             .            .
CD44       .  .         .            .             .            .
NOCT       .  .         .            .             .            .
NINJ1      .  .         .            .             .            .
ZNF331     .  .         .            .             .            .
B3GNT5     .  .         .            .             .            .
GSTO1      .  .         .            .             .            .
ITGA5      .  .         .            .             .            .
ZNF267     .  .         .            .             .            .
MYH9       .  .         .            .             .            .
PTP4A2     .  .         .            .             .            .
TNFRSF1B   .  .         .            .             .            .
PHLDA1     .  .         .            .             .            .
DUSP2      .  .         .            .             .            .
KMO        .  .         .            .             .            .
VOPP1      .  .         .            .             .            .
USP36      .  .         .            .             .            .
NFAT5      .  .         .            .             .            .
TNFAIP3    .  .         .            .             .            .
FGR        .  .         .            .             .            .
CD58       .  .         .            .             .            .
USP3       .  .         .            .             .            .
BID        .  .         .            .             .            .
ARFGAP3    .  .         .            .             .            .
ELK3       .  .         .            .             .            .
MCL1       .  .         .            .             .            .
NDUFS5     .  .         .            .             .            .
CITED2     .  .         .            .             .            .
ARHGAP31   .  .         .            .             .            .
PPP1R15A   .  .         .            .             .            .
ZFP36      .  .         .            .             .            .
PIM3       .  .         .            .             .            .
SMS        .  .         .            .             .            .
CD302      .  .         .            .             .            .
CDC42EP3   .  .         .            .             .            .
MYOF       .  .         .            .             .            .
DEK        .  .         .            .             .            .
CD83       .  .         .            .             .            .
FLOT1      .  .         .            .             .            .
SPOCK2     .  .         .            .             .            .
SRSF5      .  .         .            .             .            .
PIK3R5     .  .         .            .             .            .
PDE4B      .  .         .            .             .            .
CAST       .  .         .            .             .            .
MSN        .  .         .            .             .            .
SNX9       .  .         .            .             .            .
AZIN1      .  .         .            .             .            .
METRNL     .  .         .            .             .            .
CXCR4      .  .         .            .             .            .
LMNA       .  .         .            .             .            .
TMSB4X     .  .         .            .             .            .
AREG       .  .         .            .             .            .
ARL4C      .  .         .            .             .            .
EVI2B      .  .         .            .             .            .
ADA2       .  .         .            .             .            .
UBE2J1     .  .         .            .             .            .
BTG2       .  .         .            .             .            .
B2M        .  .         .            .             .            .
SNU13      .  .         .            .             .            .
KLF10      .  .         .            .             .            .
USP12      .  .         .            .             .            .
RIPK1      .  .         .            .             .            .
IL6R       .  .         .            .             .            .
HNRNPUL1   .  .         .            .             .            .
SAMSN1     .  .         .            .             .            .
CCNH       .  .         .            .             .            .
HERPUD2    .  .         .            .             .            .
HMGB2      .  .         .            .             .            .
JUND       .  .         .            .             .            .
NCOA4      .  .         .            .             .            .
TIPARP     .  .         .            .             .            .
CD96       .  .         .            .             .            .
BHLHE40    .  .         .            .             .            .
TSC22D3    .  .         .            .             .            .
VIM        .  .         .            .             .            .
SUSD6      .  .         .            .             .            .
ITM2B      .  .         .            .             .            .
ABCA1      .  .         .            .             .            .
SLC7A5     .  .         .            .             .            .
B4GALT1    .  .         .            .             .            .
NACA       .  .         .            .             .            .
ARL8B      .  .         .            .             .            .
COTL1      .  .         .            .             .            .
FNIP2      .  .         .            .             .            .
LINC00910  .  .         .            .             .            .
TPI1       .  .         .            .             .            .

[1] 0.01228808

In [11]:
best_coefficients <- rnaRes_top_500_genes$coefMat[, best_model_index]
head(best_coefficients)

     AP1S2  LINC01588      PNRC1   SERPINB9     NFKBIZ       FTH1
0.00000000 0.00000000 0.00000000 0.05909241 0.00000000 0.00000000

In [12]:
# First, let's check how many genes we currently have
ncol(uke_bulk_seq) 

# Get the list of variables/genes that were used in training
# Assuming your model is a glmnet model
model_genes <- names(best_coefficients)  # This should give us all 23852 gene names

# Check which genes are missing in your current dataset
current_genes <- colnames(uke_bulk_seq)
missing_genes <- setdiff(current_genes, model_genes)
print(paste("Number of unwanted genes:", length(missing_genes)))

# Create a new dataframe with all required genes
# First, get the sample IDs (row names from your current data)
#sample_ids <- rownames(uke_bulk_seq)
uke_bulk_seqx = uke_bulk_seq[,model_genes]
ncol(uke_bulk_seqx)

[1] 14738

[1] "Number of unwanted genes: 14340"

[1] 398

In [51]:
length(best_coefficients)

[1] 398

In [13]:
complete_data = uke_bulk_seqx

In [14]:
head(complete_data)

           AP1S2      LINC01588  PNRC1       SERPINB9     NFKBIZ     FTH1
LCLC100001 -0.2426719 -1.1875648  0.76801567  0.172145045  0.8607413 -0.4132146
LCLC100002 -0.5647095 -1.1875648  1.25240366  1.155739782 -1.4074566  1.1950818
LCLC100003  0.1484269  0.2022457  0.60566169 -0.004929476  1.7470463  1.7248060
LCLC100004 -2.2038918 -0.3274034  1.75274366 -1.462663462 -0.9383149  0.5517481
LCLC100005  1.4735246  1.3319067 -0.08018952  1.387820403  1.0387557 -1.0219921
LCLC100006 -0.5719513  0.4606713 -0.87510963 -1.770185973 -0.7353218  0.1584025
           FLNA        TMEM107    RNF19B     PFKFB3     ⋯ TAOK1
LCLC100001 -1.19006300  0.5218570 -1.3878204 -0.7033956 ⋯  0.7002426
LCLC100002  0.59975044  1.6530120 -1.7584985  1.0515225 ⋯ -2.0405263
LCLC100003 -0.08018952 -0.1521660  0.9006992  1.0303377 ⋯  1.9341284
LCLC100004 -0.51340276 -1.3439711  0.2758097  0.7385554 ⋯  1.0178458
LCLC100005 -0.10742191  1.1089464  2.3326660 -2.2327507 ⋯  1.1654065
LCLC100006  0.44157000 -0.7846735  1.4008511  0.2834988 ⋯ -0.2860655
           SERBP1      ASH1L      SMG7         IGF1R      FKBP5
LCLC100001  0.30021679  0.9364027  0.001232364 -0.0653618  0.2490228
LCLC100002  0.43478731 -1.5716682  0.815220825  1.0219921  0.8083675
LCLC100003 -0.19847361  2.1037733  1.160559602  0.8117894  1.0261559
LCLC100004 -2.29676373  1.4771839  0.675263518  1.6827231  2.6577564
LCLC100005 -0.11114114  0.4388545 -0.222413333 -0.4388545 -1.8596844
LCLC100006 -0.02834817  0.9421497  1.274301631 -0.5374544 -0.2886342
           PRKCB       PDE3B      LINC01619  ADIPOR2
LCLC100001 -0.07277366  0.3745911  0.2325307  0.2186252
LCLC100002 -1.54673468  0.6385631  1.4995668 -1.0493828
LCLC100003  2.05051039  0.9212266  0.1821599 -0.2350637
LCLC100004 -0.15465986  1.2605446  0.7729905 -0.3798841
LCLC100005  1.04299239  0.8823619  0.6385631  0.3092534
LCLC100006  0.19596048 -0.3002168 -0.5909226 -0.4827097

In [15]:
write.csv(complete_data, "uke_top_500_genes_dataset_for_making_predictions.csv")

In [54]:

best_model_index <- which.max(rnaRes_top_500_genes$r2Train)
best_model_index
# Extract the best model
best_model <- rnaRes_top_500_genes$modelList[[best_model_index]]
best_model
# Get the optimal lambda value for the best model
best_lambda <- rnaRes_top_500_genes$lambdaList[best_model_index]
best_lambda

set.seed(5863)
# Generate predictions on your data
predicted_values <- predict(best_model, newx = as.matrix(complete_data), s = best_lambda)

[1] 16

Call:  cv.glmnet(x = X.train, y = y.train, type.measure = "mse", nfolds = folds,      alpha = alpha, standardize = TRUE, intercept = TRUE, family = "gaussian")

Measure: Mean-Squared Error

      Lambda Index Measure       SE Nonzero
min 0.006712   100 0.08936 0.006410      59
1se 0.012288    87 0.09557 0.008559      53

[1] 0.01228808

In [55]:
as.data.frame(predicted_values)

           s1
LCLC100001  0.08045102
LCLC100002  0.17444418
LCLC100003 -0.20706624
LCLC100004  0.17511966
LCLC100005 -0.34439143
LCLC100006 -0.35838816
LCLC100007 -0.82824099
LCLC100008  0.05741509
LCLC100009 -0.26330717
LCLC100010 -0.01984045
LCLC100011 -0.40725173
LCLC100012  0.78345700
LCLC100013 -0.43292744
LCLC100014  0.05101340
LCLC100015 -0.16434055
LCLC100016 -0.12280007
LCLC100017  0.29107186
LCLC100018  0.09238166
LCLC100019  0.83893524
LCLC100020  0.38007263
LCLC100021 -0.24873196
LCLC100022  0.63798082
LCLC100023  0.34129994
LCLC100024 -0.08762922
LCLC100025 -0.87487120
LCLC100027  0.36945938
LCLC100028  0.46592641
LCLC100029  0.03934815
LCLC100030 -0.18699620
LCLC100031  0.22725100
⋮          ⋮
LCSC200072  0.44237591
LCSC200073  0.41021466
LCSC200168  0.42594107
LCSC300001 -0.62864735
LCSC300005 -0.53065721
LCSC300006 -0.01368566
LCSC300014  0.19881103
LCSC300015  0.18663415
LCSC300016  0.22395619
LCSC300018 -0.64993972
LCSC300019 -0.01076463
LCSC300028 -0.26275865
LCSC300032 -0.20935381
LCSC300038  0.24129805
LCSC300041 -0.64486106
LCSC300048 -0.14453608
LCSC300049 -0.22536876
LCSC300052  0.09735179
LCSC300055 -0.07027417
LCSC300056  0.22056663
LCSC300057 -0.46377739
LCSC300061 -0.27614906
LCSC300063  0.14562154
LCSC300065 -0.22161208
LCSC300066 -0.33386753
LCSC300068 -1.66238496
LCSC300069  0.72213398
LCSC300070  0.06616237
LCSC300072 -0.36947840
LCSC300073  0.19054750

In [56]:
write.csv(as.data.frame(predicted_values), "predicted_values_top_500_factor3_genes.csv")