In [1]:
source('/ictstr01/home/icb/bhavishya.nelakuditi/mofa_workflow/scripts/MS0_Libraries.r')

[1] "/ictstr01/home/icb/bhavishya.nelakuditi/miniconda3/envs/my_jupyter_env/lib/R/library/"

Warning message:
“package ‘ggplot2’ was built under R version 4.3.3”
Warning message:
“package ‘tibble’ was built under R version 4.3.3”
Warning message:
“package ‘purrr’ was built under R version 4.3.3”
Warning message:
“package ‘stringr’ was built under R version 4.3.3”
Warning message:
“package ‘forcats’ was built under R version 4.3.3”
Warning message:
“package ‘lubridate’ was built under R version 4.3.3”
── Attaching core tidyverse packages ──────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ lubridate 1.9.3     ✔ tibble    3.2.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Warning message:
“package ‘backports’ was built under R version 4.3.3”

Attaching package: ‘backports’


The following object is masked from ‘package:purrr’:

    %||%


Warning message:
“package ‘ggraph’ was built under R version 4.3.3”
Warning message:
“package ‘ggpubr’ was built under R version 4.3.3”
Warning message:
“package ‘corrplot’ was built under R version 4.3.3”
corrplot 0.94 loaded


Attaching package: ‘data.table’


The following objects are masked from ‘package:lubridate’:

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year


The following objects are masked from ‘package:dplyr’:

    between, first, last


The following object is masked from ‘package:purrr’:

    transpose


Warning message:
“package ‘reshape2’ was built under R version 4.3.3”

Attaching package: ‘reshape2’


The following objects are masked from ‘package:data.table’:

    dcast, melt


The following object is masked from ‘package:tidyr’:

    smiths


Warning message:
“package ‘gridExtra’ was built under R version 4.3.3”

Attaching package: ‘gridExtra’


The following object is masked from ‘package:dplyr’:

    combine


Warning message:
“package ‘scales’ was built under R version 4.3.3”

Attaching package: ‘scales’


The following object is masked from ‘package:purrr’:

    discard


The following object is masked from ‘package:readr’:

    col_factor



Attaching package: ‘reticulate’


The following object is masked from ‘package:backports’:

    import



Attaching package: ‘MOFA2’


The following object is masked from ‘package:stats’:

    predict

In [2]:
bulkseq = read.csv("02_Combined_Data_uke_bulk_seq_INTEGRATED.csv")
head(bulkseq)

  X sample_id  variable          value      type         gene
1 1 LCLC100001 uke_bulk_seq__A2M  0.5997504 uke_bulk_seq A2M
2 2 LCLC100002 uke_bulk_seq__A2M -0.6721709 uke_bulk_seq A2M
3 3 LCLC100003 uke_bulk_seq__A2M  0.4524649 uke_bulk_seq A2M
4 4 LCLC100004 uke_bulk_seq__A2M  0.5303487 uke_bulk_seq A2M
5 5 LCLC100005 uke_bulk_seq__A2M -0.6721709 uke_bulk_seq A2M
6 6 LCLC100006 uke_bulk_seq__A2M  1.3409367 uke_bulk_seq A2M

In [3]:
wide_bulkseq <- reshape2::dcast(bulkseq, sample_id ~ gene, value.var = "value")
head(wide_bulkseq)

  sample_id  A2M        A2ML1       A4GALT     AAAS       AACS       AAGAB
1 LCLC100001  0.5997504 -0.02958105  1.8067808 -0.6970965  0.1921931  0.1546599
2 LCLC100002 -0.6721709 -0.02958105 -0.3222069  0.9576292  0.6325305 -1.1135164
3 LCLC100003  0.4524649 -0.02958105  0.6876994 -1.1461798  0.6629312  0.5879902
4 LCLC100004  0.5303487 -0.02958105 -0.3222069  0.5035856 -0.6160577  0.2022457
5 LCLC100005 -0.6721709 -0.02958105 -0.3222069 -0.3535220 -0.6160577  0.9812888
6 LCLC100006  1.3409367 -0.02958105  1.8195347  1.7193771 -0.6160577  1.2052108
  AAK1        AAMDC      AAMP        ⋯ ZUP1        ZW10        ZWILCH
1  1.06446307  0.1446899 -0.36930857 ⋯  2.26359850  0.95762923  1.2743016
2 -1.87375923 -0.9654557 -0.08637275 ⋯  0.07153808 -0.10990123  1.4555175
3 -0.05548483  1.2052108 -0.46341372 ⋯  0.28221615 -0.09503488 -0.1173433
4 -0.25029415 -0.8751096 -1.25510808 ⋯  0.86431666  0.00369710 -1.0199167
5  1.38139251  0.8152208 -0.53034867 ⋯ -1.32892068 -0.97532273  0.6783626
6  0.68769942  1.0366443  0.34566186 ⋯ -0.51059285 -0.97532273  2.0024992
  ZWINT      ZXDA       ZXDB       ZXDC       ZYG11B      ZYX
1  1.0472479  1.3687052  0.4172446 -0.4551970 -0.08018952 -1.1227267
2 -0.4634137 -0.3522105 -0.4868678 -0.6175483 -0.56470948  0.9595803
3 -0.4634137 -0.3522105  0.8430269  0.6265207  2.12686067 -0.5531837
4 -0.4634137  2.2967637 -0.4868678  0.4716619  0.94407222 -0.2135793
5  0.8896609  1.2001309 -0.4868678  0.3745911 -0.96545569 -1.4626635
6  0.9933270 -0.3522105 -0.4868678 -1.7302862  1.03664427 -0.2299992
  ZZEF1
1  0.977307558
2 -0.145935296
3  0.662931180
4  0.681468296
5 -0.237598230
6  0.001232364

In [4]:
# Get all column names except the first one
column_names_wide_bulkseq = colnames(wide_bulkseq)
length(column_names_wide_bulkseq)
column_names_wide_bulkseq

[1] 15093

    [1] "sample_id"  "A2M"        "A2ML1"      "A4GALT"     "AAAS"
    [6] "AACS"       "AAGAB"      "AAK1"       "AAMDC"      "AAMP"
   [11] "AANAT"      "AAR2"       "AARD"       "AARS2"      "AARSD1"
   [16] "AASDH"      "AASDHPPT"   "AASS"       "AATBC"      "AATF"
   [21] "AATK"       "ABALON"     "ABAT"       "ABCA1"      "ABCA10"
   [26] "ABCA12"     "ABCA13"     "ABCA2"      "ABCA3"      "ABCA4"
   [31] "ABCA5"      "ABCA6"      "ABCA7"      "ABCA9"      "ABCB1"
   [36] "ABCB10"     "ABCB11"     "ABCB4"      "ABCB5"      "ABCB7"
   [41] "ABCB8"      "ABCB9"      "ABCC1"      "ABCC10"     "ABCC11"
   [46] "ABCC2"      "ABCC3"      "ABCC4"      "ABCC5"      "ABCC6"
   [51] "ABCC8"      "ABCC9"      "ABCD1"      "ABCD2"      "ABCD3"
   [56] "ABCD4"      "ABCE1"      "ABCF1"      "ABCF2"      "ABCF3"
   [61] "ABCG1"      "ABCG2"      "ABHD1"      "ABHD10"     "ABHD11"
   [66] "ABHD12"     "ABHD12B"    "ABHD13"     "ABHD14A"    "ABHD14B"
   [71] "ABHD15"     "ABHD16A"    "ABHD17A"    "ABHD17B"    "ABHD17C"
   [76] "ABHD18"     "ABHD2"      "ABHD3"      "ABHD4"      "ABHD5"
   [81] "ABHD6"      "ABHD8"      "ABI1"       "ABI2"       "ABI3"
   [86] "ABI3BP"     "ABITRAM"    "ABL1"       "ABL2"       "ABLIM1"
   [91] "ABLIM2"     "ABLIM3"     "ABO"        "ABR"        "ABRA"
   [96] "ABRACL"     "ABRAXAS1"   "ABRAXAS2"   "ABT1"       "ABTB1"
  [101] "ABTB2"      "ACAA1"      "ACAA2"      "ACACA"      "ACACB"
  [106] "ACAD10"     "ACAD11"     "ACAD8"      "ACAD9"      "ACADL"
  [111] "ACADM"      "ACADS"      "ACADSB"     "ACADVL"     "ACAN"
  [116] "ACAP1"      "ACAP2"      "ACAP3"      "ACAT1"      "ACAT2"
  [121] "ACBD3"      "ACBD4"      "ACBD5"      "ACBD6"      "ACBD7"
  [126] "ACCS"       "ACD"        "ACE"        "ACER1"      "ACER2"
  [131] "ACER3"      "ACHE"       "ACIN1"      "ACKR1"      "ACKR2"
  [136] "ACKR3"      "ACKR4"      "ACLY"       "ACMSD"      "ACO1"
  [141] "ACO2"       "ACOD1"      "ACOT1"      "ACOT11"     "ACOT12"
  [146] "ACOT13"     "ACOT2"      "ACOT4"      "ACOT7"      "ACOT8"
  [151] "ACOT9"      "ACOX1"      "ACOX2"      "ACOX3"      "ACOXL"
  [156] "ACP1"       "ACP2"       "ACP5"       "ACP6"       "ACP7"
  [161] "ACRBP"      "ACSBG1"     "ACSF2"      "ACSF3"      "ACSL1"
  [166] "ACSL3"      "ACSL4"      "ACSL5"      "ACSL6"      "ACSM1"
  [171] "ACSM2A"     "ACSM3"      "ACSS1"      "ACSS2"      "ACSS3"
  [176] "ACTA1"      "ACTA2"      "ACTB"       "ACTG1"      "ACTL10"
  [181] "ACTL6A"     "ACTN1"      "ACTN3"      "ACTN4"      "ACTR10"
  [186] "ACTR1A"     "ACTR1B"     "ACTR2"      "ACTR3"      "ACTR3B"
  [191] "ACTR3C"     "ACTR5"      "ACTR6"      "ACTR8"      "ACTRT3"
  [196] "ACVR1"      "ACVR1B"     "ACVR1C"     "ACVR2A"     "ACVR2B"
  [201] "ACVRL1"     "ACY1"       "ACY3"       "ACYP1"      "ACYP2"
  [206] "ADA"        "ADA2"       "ADAL"       "ADAM10"     "ADAM11"
  [211] "ADAM12"     "ADAM15"     "ADAM17"     "ADAM19"     "ADAM20"
  [216] "ADAM21"     "ADAM22"     "ADAM23"     "ADAM28"     "ADAM29"
  [221] "ADAM32"     "ADAM8"      "ADAM9"      "ADAMDEC1"   "ADAMTS1"
  [226] "ADAMTS10"   "ADAMTS15"   "ADAMTS17"   "ADAMTS2"    "ADAMTS3"
  [231] "ADAMTS4"    "ADAMTS5"    "ADAMTS6"    "ADAMTS7"    "ADAMTSL4"
  [236] "ADAMTSL5"   "ADAP1"      "ADAP2"      "ADAR"       "ADARB1"
  [241] "ADARB2"     "ADAT1"      "ADAT2"      "ADAT3"      "ADCK1"
  [246] "ADCK2"      "ADCK5"      "ADCY10"     "ADCY3"      "ADCY4"
  [251] "ADCY5"      "ADCY6"      "ADCY7"      "ADCY9"      "ADD1"
  [256] "ADD2"       "ADD3"       "ADGB"       "ADGRA2"     "ADGRA3"
  [261] "ADGRB2"     "ADGRB3"     "ADGRD1"     "ADGRD2"     "ADGRE1"
  [266] "ADGRE2"     "ADGRE3"     "ADGRE5"     "ADGRF3"     "ADGRG1"
  [271] "ADGRG2"     "ADGRG3"     "ADGRG5"     "ADGRG6"     "ADGRG7"
  [276] "ADGRL1"     "ADGRL2"     "ADGRV1"     "ADH5"       "ADH6"
  [281] "ADHFE1"     "ADI1"       "ADIPOR1"    "ADIPOR2"    "ADIRF"
  [286] "ADK"        "ADM"        "ADM2"       "ADM5"       "ADNP"
  [291] "ADNP2"      "ADO"        "ADORA2A"    "ADORA2B"    "ADORA3"
  [296] "ADPGK"      "ADPRH"      "ADPRHL1"    "ADPRM"      "ADRA2A"
  [301] "ADRA2B"     "ADRB1"      "ADRB2"      "ADRM1"      "ADSL"
  [306] "ADTRP"      "AEBP1"      "AEBP2"      "AEN"        "AFAP1"
  [311] "AFAP1L1"    "AFAP1L2"    "AFDN"       "AFF1"       "AFF2"
  [316] "AFF3"       "AFF4"       "AFG1L"      "AFG3L2"     "AFMID"
  [321] "AFTPH"      "AGA"        "AGAP1"      "AGAP2"      "AGAP3"
  [326] "AGAP4"      "AGAP9"      "AGBL2"      "AGBL3"      "AGBL5"
  [331] "AGER"       "AGFG1"      "AGFG2"      "AGGF1"      "AGK"
  [336] "AGL"        "AGMAT"      "AGMO"       "AGO1"       "AGO2"
  [341] "AGO3"       "AGO4"       "AGPAT1"     "AGPAT2"     "AGPAT3"
  [346] "AGPAT4"     "AGPAT5"     "AGPS"       "AGRN"       "AGRP"
  [351] "AGTPBP1"    "AGTRAP"     "AHCTF1"     "AHCY"       "AHCYL1"
  [356] "AHCYL2"     "AHDC1"      "AHI1"       "AHNAK"      "AHR"
  [361] "AHSA1"      "AHSP"       "AICDA"      "AIDA"       "AIF1"
  [366] "AIF1L"      "AIFM1"      "AIFM2"      "AIFM3"      "AIG1"
  [371] "AIM2"       "AIMP1"      "AIMP2"      "AIP"        "AIRE"
  [376] "AIRN"       "AJAP1"      "AJM1"       "AK1"        "AK2"
  [381] "AK3"        "AK4"        "AK5"        "AK6"        "AK7"
  [386] "AK9"        "AKAP1"      "AKAP10"     "AKAP11"     "AKAP12"
  [391] "AKAP13"     "AKAP17A"    "AKAP3"      "AKAP5"      "AKAP6"
  [396] "AKAP7"      "AKAP8"      "AKAP8L"     "AKAP9"      "AKIP1"
  [401] "AKIRIN1"    "AKIRIN2"    "AKNA"       "AKNAD1"     "AKR1A1"
  [406] "AKR1B1"     "AKR1C1"     "AKR1C2"     "AKR1C3"     "AKR1C4"
  [411] "AKR1E2"     "AKR7A2"     "AKR7A3"     "AKT1"       "AKT1S1"
  [416] "AKT2"       "AKT3"       "AKTIP"      "ALAD"       "ALAS1"
  [421] "ALAS2"      "ALCAM"      "ALDH16A1"   "ALDH18A1"   "ALDH1A1"
  [426] "ALDH1A2"    "ALDH1A3"    "ALDH1B1"    "ALDH1L2"    "ALDH2"
  [431] "ALDH3A2"    "ALDH3B1"    "ALDH4A1"    "ALDH5A1"    "ALDH6A1"
  [436] "ALDH7A1"    "ALDH8A1"    "ALDH9A1"    "ALDOA"      "ALDOC"
  [441] "ALG1"       "ALG10"      "ALG10B"     "ALG11"      "ALG12"
  [446] "ALG13"      "ALG14"      "ALG1L2"     "ALG2"       "ALG3"
  [451] "ALG5"       "ALG6"       "ALG8"       "ALG9"       "ALK"
  [456] "ALKAL2"     "ALKBH1"     "ALKBH2"     "ALKBH3"     "ALKBH4"
  [461] "ALKBH5"     "ALKBH6"     "ALKBH7"     "ALKBH8"     "ALMS1"
  [466] "ALOX12"     "ALOX12B"    "ALOX15"     "ALOX15B"    "ALOX5"
  [471] "ALOX5AP"    "ALOXE3"     "ALPK1"      "ALPK3"      "ALPL"
  [476] "ALS2"       "ALS2CL"     "ALX3"       "ALYREF"     "AMACR"
  [481] "AMBRA1"     "AMD1"       "AMDHD1"     "AMDHD2"     "AMER1"
  [486] "AMFR"       "AMIGO1"     "AMIGO2"     "AMIGO3"     "AMMECR1"
  [491] "AMMECR1L"   "AMN"        "AMN1"       "AMOT"       "AMOTL1"
  [496] "AMPD2"      "AMPD3"      "AMPH"       "AMT"        "AMY2B"
  [501] "AMZ1"       "AMZ2"       "ANAPC1"     "ANAPC10"    "ANAPC11"
  [506] "ANAPC13"    "ANAPC15"    "ANAPC16"    "ANAPC2"     "ANAPC4"
  [511] "ANAPC5"     "ANAPC7"     "ANG"        "ANGEL1"     "ANGEL2"
  [516] "ANGPT1"     "ANGPT2"     "ANGPTL1"    "ANGPTL2"    "ANGPTL5"
  [521] "ANGPTL6"    "ANK1"       "ANK2"       "ANK3"       "ANKAR"
  [526] "ANKDD1A"    "ANKDD1B"    "ANKEF1"     "ANKFY1"     "ANKH"
  [531] "ANKHD1"     "ANKIB1"     "ANKK1"      "ANKLE1"     "ANKLE2"
  [536] "ANKMY1"     "ANKMY2"     "ANKRA2"     "ANKRD10"    "ANKRD11"
  [541] "ANKRD12"    "ANKRD13A"   "ANKRD13B"   "ANKRD13C"   "ANKRD13D"
  [546] "ANKRD16"    "ANKRD17"    "ANKRD18A"   "ANKRD18B"   "ANKRD2"
  [551] "ANKRD20A1"  "ANKRD22"    "ANKRD23"    "ANKRD24"    "ANKRD26"
  [556] "ANKRD27"    "ANKRD28"    "ANKRD30B"   "ANKRD30BL"  "ANKRD31"
  [561] "ANKRD33B"   "ANKRD34A"   "ANKRD34B"   "ANKRD35"    "ANKRD36"
  [566] "ANKRD36B"   "ANKRD36C"   "ANKRD37"    "ANKRD39"    "ANKRD40"
  [571] "ANKRD40CL"  "ANKRD42"    "ANKRD44"    "ANKRD46"    "ANKRD49"
  [576] "ANKRD50"    "ANKRD52"    "ANKRD54"    "ANKRD55"    "ANKRD6"
  [581] "ANKRD61"    "ANKRD62"    "ANKRD9"     "ANKS1A"     "ANKS1B"
  [586] "ANKS3"      "ANKS6"      "ANKUB1"     "ANKZF1"     "ANLN"
  [591] "ANO10"      "ANO2"       "ANO5"       "ANO6"       "ANO7"
  [596] "ANO8"       "ANO9"       "ANOS1"      "ANP32A"     "ANP32B"
  [601] "ANP32E"     "ANPEP"      "ANTKMT"     "ANTXR1"     "ANTXR2"
  [606] "ANTXRL"     "ANXA1"      "ANXA11"     "ANXA2"      "ANXA2R"
  [611] "ANXA3"      "ANXA4"      "ANXA5"      "ANXA6"      "ANXA7"
  [616] "ANXA9"      "AOAH"       "AOC1"       "AOC2"       "AOC3"
  [621] "AOPEP"      "AP1AR"      "AP1B1"      "AP1G1"      "AP1G2"
  [626] "AP1M1"      "AP1M2"      "AP1S1"      "AP1S2"      "AP1S3"
  [631] "AP2A1"      "AP2A2"      "AP2B1"      "AP2M1"      "AP2S1"
  [636] "AP3B1"      "AP3B2"      "AP3D1"      "AP3M1"      "AP3M2"
  [641] "AP3S1"      "AP3S2"      "AP4B1"      "AP4E1"      "AP4M1"
  [646] "AP4S1"      "AP5B1"      "AP5M1"      "AP5S1"      "AP5Z1"
  [651] "APAF1"      "APBA1"      "APBA2"      "APBA3"      "APBB1"
  [656] "APBB1IP"    "APBB2"      "APBB3"      "APC"        "APC2"
  [661] "APCDD1"     "APEH"       "APEX1"      "APEX2"      "APH1A"
  [666] "APH1B"      "API5"       "APIP"       "APLF"       "APLP2"
  [671] "APMAP"      "APOA1"      "APOBEC2"    "APOBEC3A"   "APOBEC3B"
  [676] "APOBEC3C"   "APOBEC3D"   "APOBEC3F"   "APOBEC3G"   "APOBEC3H"
  [681] "APOBR"      "APOC1"      "APOD"       "APOE"       "APOL1"
  [686] "APOL2"      "APOL3"      "APOL4"      "APOL6"      "APOLD1"
  [691] "APOM"       "APOO"       "APOOL"      "APP"        "APPBP2"
  [696] "APPL1"      "APPL2"      "APRT"       "APTR"       "APTX"
  [701] "AQP1"       "AQP10"      "AQP11"      "AQP3"       "AQP9"
  [706] "AQR"        "AR"         "ARAF"       "ARAP1"      "ARAP2"
  [711] "ARAP3"      "ARCN1"      "AREG"       "AREL1"      "ARF1"
  [716] "ARF3"       "ARF4"       "ARF5"       "ARF6"       "ARFGAP1"
  [721] "ARFGAP2"    "ARFGAP3"    "ARFGEF1"    "ARFGEF2"    "ARFGEF3"
  [726] "ARFIP1"     "ARFIP2"     "ARFRP1"     "ARG1"       "ARG2"
  [731] "ARGFX"      "ARGLU1"     "ARHGAP1"    "ARHGAP10"   "ARHGAP11A"
  [736] "ARHGAP11B"  "ARHGAP12"   "ARHGAP15"   "ARHGAP17"   "ARHGAP18"
  [741] "ARHGAP19"   "ARHGAP21"   "ARHGAP22"   "ARHGAP23"   "ARHGAP24"
  [746] "ARHGAP25"   "ARHGAP26"   "ARHGAP27"   "ARHGAP29"   "ARHGAP30"
  [751] "ARHGAP31"   "ARHGAP32"   "ARHGAP33"   "ARHGAP35"   "ARHGAP4"
  [756] "ARHGAP42"   "ARHGAP44"   "ARHGAP45"   "ARHGAP5"    "ARHGAP6"
  [761] "ARHGAP8"    "ARHGAP9"    "ARHGDIA"    "ARHGDIB"    "ARHGEF1"
  [766] "ARHGEF10"   "ARHGEF10L"  "ARHGEF11"   "ARHGEF12"   "ARHGEF17"
  [771] "ARHGEF18"   "ARHGEF19"   "ARHGEF2"    "ARHGEF26"   "ARHGEF28"
  [776] "ARHGEF3"    "ARHGEF33"   "ARHGEF35"   "ARHGEF37"   "ARHGEF38"
  [781] "ARHGEF39"   "ARHGEF4"    "ARHGEF40"   "ARHGEF5"    "ARHGEF6"
  [786] "ARHGEF7"    "ARHGEF9"    "ARID1A"     "ARID1B"     "ARID2"
  [791] "ARID3A"     "ARID3B"     "ARID4A"     "ARID4B"     "ARID5A"
  [796] "ARID5B"     "ARIH1"      "ARIH2"      "ARIH2OS"    "ARL1"
  [801] "ARL10"      "ARL11"      "ARL13B"     "ARL14"      "ARL14EP"
  [806] "ARL15"      "ARL16"      "ARL17A"     "ARL17B"     "ARL2"
  [811] "ARL2BP"     "ARL3"       "ARL4A"      "ARL4C"      "ARL4D"
  [816] "ARL5A"      "ARL5B"      "ARL6"       "ARL6IP1"    "ARL6IP4"
  [821] "ARL6IP5"    "ARL6IP6"    "ARL8A"      "ARL8B"      "ARL9"
  [826] "ARLNC1"     "ARMC1"      "ARMC10"     "ARMC12"     "ARMC2"
  [831] "ARMC3"      "ARMC5"      "ARMC6"      "ARMC7"      "ARMC8"
  [836] "ARMC9"      "ARMCX1"     "ARMCX2"     "ARMCX3"     "ARMCX4"
  [841] "ARMCX5"     "ARMCX6"     "ARMH1"      "ARMH2"      "ARMH3"
  [846] "ARMH4"      "ARMT1"      "ARNT"       "ARNT2"      "ARPC1A"
  [851] "ARPC1B"     "ARPC2"      "ARPC3"      "ARPC4"      "ARPC5"
  [856] "ARPC5L"     "ARPIN"      "ARPP19"     "ARPP21"     "ARRB1"
  [861] "ARRB2"      "ARRDC1"     "ARRDC2"     "ARRDC3"     "ARRDC4"
  [866] "ARRDC5"     "ARSA"       "ARSB"       "ARSD"       "ARSG"
  [871] "ARSJ"       "ARSK"       "ART3"       "ART4"       "ARV1"
  [876] "ARVCF"      "ASAH1"      "ASAH2"      "ASAH2B"     "ASAP1"
  [881] "ASAP2"      "ASAP3"      "ASB1"       "ASB13"      "ASB14"
  [886] "ASB15"      "ASB16"      "ASB2"       "ASB3"       "ASB6"
  [891] "ASB7"       "ASB8"       "ASB9"       "ASCC1"      "ASCC2"
  [896] "ASCC3"      "ASCL2"      "ASDURF"     "ASF1A"      "ASF1B"
  [901] "ASGR1"      "ASGR2"      "ASH1L"      "ASH2L"      "ASIC3"
  [906] "ASIP"       "ASL"        "ASMT"       "ASMTL"      "ASNS"
  [911] "ASNSD1"     "ASPA"       "ASPH"       "ASPHD1"     "ASPHD2"
  [916] "ASPM"       "ASPN"       "ASPRV1"     "ASPSCR1"    "ASRGL1"
  [921] "ASS1"       "ASTE1"      "ASTL"       "ASTN2"      "ASXL1"
  [926] "ASXL2"      "ATAD1"      "ATAD2"      "ATAD2B"     "ATAD3A"
  [931] "ATAD3B"     "ATAD3C"     "ATAD5"      "ATAT1"      "ATCAY"
  [936] "ATE1"       "ATF1"       "ATF2"       "ATF3"       "ATF4"
  [941] "ATF5"       "ATF6"       "ATF6B"      "ATF7"       "ATF7IP"
  [946] "ATF7IP2"    "ATG10"      "ATG101"     "ATG12"      "ATG13"
  [951] "ATG14"      "ATG16L1"    "ATG16L2"    "ATG2A"      "ATG2B"
  [956] "ATG3"       "ATG4A"      "ATG4B"      "ATG4C"      "ATG4D"
  [961] "ATG5"       "ATG7"       "ATG9A"      "ATG9B"      "ATIC"
  [966] "ATL1"       "ATL2"       "ATL3"       "ATM"        "ATMIN"
  [971] "ATN1"       "ATOH8"      "ATOX1"      "ATP10A"     "ATP10D"
  [976] "ATP11A"     "ATP11B"     "ATP11C"     "ATP13A1"    "ATP13A2"
  [981] "ATP13A3"    "ATP13A4"    "ATP1A1"     "ATP1A3"     "ATP1A4"
  [986] "ATP1B1"     "ATP1B2"     "ATP1B3"     "ATP23"      "ATP2A1"
  [991] "ATP2A2"     "ATP2A3"     "ATP2B1"     "ATP2B2"     "ATP2B4"
  [996] "ATP2C1"     "ATP2C2"     "ATP5F1A"    "ATP5F1B"    "ATP5F1C"
 [1001] "ATP5F1D"    "ATP5F1E"    "ATP5IF1"    "ATP5MC1"    "ATP5MC2"
 [1006] "ATP5MC3"    "ATP5ME"     "ATP5MF"     "ATP5MG"     "ATP5MGL"
 [1011] "ATP5PB"     "ATP5PD"     "ATP5PF"     "ATP5PO"     "ATP6AP1"
 [1016] "ATP6AP1L"   "ATP6AP2"    "ATP6V0A1"   "ATP6V0A2"   "ATP6V0B"
 [1021] "ATP6V0C"    "ATP6V0D1"   "ATP6V0E1"   "ATP6V0E2"   "ATP6V1A"
 [1026] "ATP6V1B2"   "ATP6V1C1"   "ATP6V1C2"   "ATP6V1D"    "ATP6V1E1"
 [1031] "ATP6V1E2"   "ATP6V1F"    "ATP6V1G1"   "ATP6V1G2"   "ATP6V1H"
 [1036] "ATP7A"      "ATP7B"      "ATP8A1"     "ATP8A2"     "ATP8B1"
 [1041] "ATP8B2"     "ATP8B3"     "ATP8B4"     "ATP9A"      "ATP9B"
 [1046] "ATPAF1"     "ATPAF2"     "ATPSCKMT"   "ATR"        "ATRAID"
 [1051] "ATRIP"      "ATRN"       "ATRNL1"     "ATRX"       "ATXN1"
 [1056] "ATXN10"     "ATXN1L"     "ATXN2"      "ATXN2L"     "ATXN3"
 [1061] "ATXN7"      "ATXN7L1"    "ATXN7L2"    "ATXN7L3"    "ATXN7L3B"
 [1066] "AUH"        "AUNIP"      "AUP1"       "AURKA"      "AURKAIP1"
 [1071] "AURKB"      "AUTS2"      "AVEN"       "AVIL"       "AVL9"
 [1076] "AVP"        "AVPI1"      "AVPR1A"     "AVPR2"      "AXIN1"
 [1081] "AXIN2"      "AXL"        "AZI2"       "AZIN1"      "AZIN2"
 [1086] "AZU1"       "B2M"        "B3GALNT1"   "B3GALNT2"   "B3GALT1"
 [1091] "B3GALT2"    "B3GALT4"    "B3GALT6"    "B3GAT1"     "B3GAT2"
 [1096] "B3GAT3"     "B3GLCT"     "B3GNT2"     "B3GNT4"     "B3GNT5"
 [1101] "B3GNT6"     "B3GNT7"     "B3GNT8"     "B3GNT9"     "B3GNTL1"
 [1106] "B4GALNT2"   "B4GALNT3"   "B4GALNT4"   "B4GALT1"    "B4GALT2"
 [1111] "B4GALT3"    "B4GALT4"    "B4GALT5"    "B4GALT6"    "B4GALT7"
 [1116] "B4GAT1"     "B9D1"       "B9D2"       "BAALC"      "BAAT"
 [1121] "BABAM1"     "BABAM2"     "BACE1"      "BACE2"      "BACH1"
 [1126] "BACH2"      "BAD"        "BAG1"       "BAG2"       "BAG3"
 [1131] "BAG4"       "BAG5"       "BAG6"       "BAHCC1"     "BAHD1"
 [1136] "BAIAP2"     "BAIAP2L1"   "BAIAP2L2"   "BAIAP3"     "BAK1"
 [1141] "BAMBI"      "BANF1"      "BANK1"      "BANP"       "BAP1"
 [1146] "BARD1"      "BASP1"      "BATF"       "BATF2"      "BATF3"
 [1151] "BAX"        "BAZ1A"      "BAZ1B"      "BAZ2A"      "BAZ2B"
 [1156] "BBC3"       "BBIP1"      "BBOF1"      "BBS1"       "BBS10"
 [1161] "BBS12"      "BBS2"       "BBS4"       "BBS5"       "BBS7"
 [1166] "BBS9"       "BBX"        "BCAM"       "BCAP29"     "BCAP31"
 [1171] "BCAR3"      "BCAS1"      "BCAS2"      "BCAS3"      "BCAS4"
 [1176] "BCAT1"      "BCAT2"      "BCCIP"      "BCDIN3D"    "BCKDHA"
 [1181] "BCKDHB"     "BCKDK"      "BCL10"      "BCL11A"     "BCL11B"
 [1186] "BCL2"       "BCL2A1"     "BCL2L1"     "BCL2L11"    "BCL2L12"
 [1191] "BCL2L13"    "BCL2L14"    "BCL2L15"    "BCL2L2"     "BCL3"
 [1196] "BCL6"       "BCL6B"      "BCL7A"      "BCL7B"      "BCL7C"
 [1201] "BCL9"       "BCL9L"      "BCLAF1"     "BCLAF3"     "BCO2"
 [1206] "BCOR"       "BCORL1"     "BCR"        "BCS1L"      "BDH1"
 [1211] "BDH2"       "BDKRB2"     "BDNF"       "BDP1"       "BEAN1"
 [1216] "BECN1"      "BEGAIN"     "BEND2"      "BEND3"      "BEND4"
 [1221] "BEND5"      "BEND6"      "BEND7"      "BEST1"      "BEST3"
 [1226] "BEST4"      "BET1"       "BET1L"      "BEX1"       "BEX2"
 [1231] "BEX3"       "BEX4"       "BEX5"       "BFAR"       "BFSP1"
 [1236] "BFSP2"      "BHLHA15"    "BHLHE40"    "BHLHE41"    "BHMT2"
 [1241] "BICC1"      "BICD1"      "BICD2"      "BICDL1"     "BICDL2"
 [1246] "BICRA"      "BICRAL"     "BID"        "BIK"        "BIN1"
 [1251] "BIN2"       "BIN3"       "BIRC2"      "BIRC3"      "BIRC5"
 [1256] "BIRC6"      "BISPR"      "BIVM"       "BLACE"      "BLCAP"
 [1261] "BLK"        "BLM"        "BLMH"       "BLNK"       "BLOC1S1"
 [1266] "BLOC1S2"    "BLOC1S3"    "BLOC1S4"    "BLOC1S5"    "BLOC1S6"
 [1271] "BLVRA"      "BLVRB"      "BLZF1"      "BMERB1"     "BMF"
 [1276] "BMI1"       "BMP1"       "BMP2"       "BMP2K"      "BMP4"
 [1281] "BMP6"       "BMP8A"      "BMP8B"      "BMPR1A"     "BMPR1B"
 [1286] "BMPR2"      "BMS1"       "BMS1P14"    "BMT2"       "BMX"
 [1291] "BNC2"       "BNIP1"      "BNIP2"      "BNIP3"      "BNIP3L"
 [1296] "BNIPL"      "BOD1"       "BOD1L1"     "BOK"        "BOLA1"
 [1301] "BOLA2B"     "BOLA3"      "BOP1"       "BORA"       "BORCS5"
 [1306] "BORCS6"     "BORCS7"     "BORCS8"     "BPGM"       "BPHL"
 [1311] "BPI"        "BPNT1"      "BPTF"       "BRAF"       "BRAP"
 [1316] "BRAT1"      "BRCA1"      "BRCA2"      "BRCC3"      "BRD1"
 [1321] "BRD2"       "BRD3"       "BRD3OS"     "BRD4"       "BRD7"
 [1326] "BRD8"       "BRD9"       "BRDT"       "BRF1"       "BRF2"
 [1331] "BRI3"       "BRI3BP"     "BRICD5"     "BRIP1"      "BRIX1"
 [1336] "BRK1"       "BRMS1"      "BRMS1L"     "BROX"       "BRPF1"
 [1341] "BRPF3"      "BRSK1"      "BRSK2"      "BRWD1"      "BRWD3"
 [1346] "BSCL2"      "BSDC1"      "BSG"        "BSN"        "BSND"
 [1351] "BSPRY"      "BST1"       "BST2"       "BTAF1"      "BTBD1"
 [1356] "BTBD10"     "BTBD17"     "BTBD18"     "BTBD19"     "BTBD2"
 [1361] "BTBD3"      "BTBD6"      "BTBD7"      "BTBD8"      "BTBD9"
 [1366] "BTD"        "BTF3"       "BTF3L4"     "BTG1"       "BTG2"
 [1371] "BTG3"       "BTK"        "BTLA"       "BTN2A1"     "BTN2A2"
 [1376] "BTN3A1"     "BTN3A2"     "BTN3A3"     "BTNL3"      "BTNL8"
 [1381] "BTNL9"      "BTRC"       "BUB1"       "BUB1B"      "BUB3"
 [1386] "BUD13"      "BUD23"      "BUD31"      "BYSL"       "BZW1"
 [1391] "BZW2"       "C10orf105"  "C10orf143"  "C10orf67"   "C10orf88"
 [1396] "C10orf95"   "C11orf21"   "C11orf24"   "C11orf42"   "C11orf54"
 [1401] "C11orf58"   "C11orf65"   "C11orf68"   "C11orf71"   "C11orf98"
 [1406] "C12orf42"   "C12orf43"   "C12orf50"   "C12orf54"   "C12orf57"
 [1411] "C12orf60"   "C12orf71"   "C12orf75"   "C12orf76"   "C14orf119"
 [1416] "C14orf132"  "C14orf178"  "C14orf28"   "C14orf93"   "C15orf39"
 [1421] "C15orf40"   "C15orf48"   "C15orf61"   "C15orf62"   "C16orf46"
 [1426] "C16orf54"   "C16orf74"   "C16orf86"   "C16orf87"   "C16orf95"
 [1431] "C16orf96"   "C17orf100"  "C17orf107"  "C17orf113"  "C17orf49"
 [1436] "C17orf50"   "C17orf58"   "C17orf67"   "C17orf75"   "C17orf99"
 [1441] "C18orf21"   "C18orf32"   "C18orf54"   "C19orf12"   "C19orf18"
 [1446] "C19orf25"   "C19orf33"   "C19orf38"   "C19orf44"   "C19orf47"
 [1451] "C19orf53"   "C19orf73"   "C19orf84"   "C1D"        "C1GALT1"

In [5]:
cell_type_agnostic = read.csv("02_Combined_Data_cell_type_agnostic_INTEGRATED.csv")
head(cell_type_agnostic)

  X sample_id variable                 value       type               gene
1 1 HF10      cell_type_agnostic__A1BG  0.22144974 cell_type_agnostic A1BG
2 2 HF11      cell_type_agnostic__A1BG  0.30169235 cell_type_agnostic A1BG
3 3 HF12      cell_type_agnostic__A1BG  0.01292112 cell_type_agnostic A1BG
4 4 HF13      cell_type_agnostic__A1BG -1.63004123 cell_type_agnostic A1BG
5 5 HF14      cell_type_agnostic__A1BG -1.32380742 cell_type_agnostic A1BG
6 6 HF15      cell_type_agnostic__A1BG  0.87524006 cell_type_agnostic A1BG

In [6]:
wide_cell_type_agnostic <- reshape2::dcast(cell_type_agnostic, sample_id ~ gene, value.var = "value")
head(wide_cell_type_agnostic)

  sample_id A1BG        A1BG.AS1   A1CF       A2M        A2M.AS1     A2ML1
1 HF10       0.22144974  0.5877486 -0.1165502 -0.4119005 -0.27475411 -0.195041
2 HF11       0.30169235  1.0610663 -0.1165502  0.5877486 -0.65035348  1.867329
3 HF12       0.01292112 -0.3016924 -0.1165502  1.2641239  0.78408593 -0.195041
4 HF13      -1.63004123 -1.4984337 -0.1165502  1.0167374  1.10758465 -0.195041
5 HF14      -1.32380742  0.3288514 -0.1165502  1.7365070  1.15663215  1.459855
6 HF15       0.87524006  1.4598551 -0.1165502  0.4401979  0.01292112 -0.195041
  A2ML1.AS1  A3GALT2    A4GALT      ⋯ ZW10        ZWILCH     ZWINT
1  0.6503535 -0.3288514 -0.06464883 ⋯ -0.68262258 -0.5877486  0.1950410
2  1.6300412 -0.3288514 -0.06464883 ⋯ -0.01292112  0.0387720  0.6503535
3  0.4688522 -0.3288514 -0.06464883 ⋯  0.03877200  0.2214497  1.1075846
4  0.1165502 -0.3288514 -0.06464883 ⋯  0.93358993  0.6826226 -0.7840859
5  1.4598551 -0.3288514 -0.06464883 ⋯  2.04113799  0.8564434  0.1687677
6 -0.9137947 -0.3288514 -0.06464883 ⋯ -0.27475411 -0.5573042 -0.7840859
  ZXDA       ZXDB       ZXDC       ZYG11A      ZYG11B     ZYX
1 -0.7666343  1.5393809 -0.1165502  0.61874786 -1.4598551 -0.61874786
2  1.1075846  0.8197281 -1.4598551 -0.97432155  0.8564434  0.14261033
3  0.3839292  1.2641239 -0.7840859 -0.97432155  0.2214497 -0.49789692
4  0.2214497 -0.1950410  1.4598551  0.11655021 -0.4688522 -0.30169235
5 -0.7666343  1.0610663 -0.4401979 -0.09056902 -1.0610663  0.01292112
6 -0.7666343  0.5877486 -0.9743216 -0.97432155  0.0387720  0.58774863
  ZZEF1
1  0.5273679
2 -1.1566322
3 -0.1165502
4  0.8564434
5 -0.7494131
6 -0.0776024

In [7]:
column_names_wide_wide_cell_type_agnostic = colnames(wide_cell_type_agnostic)
length(column_names_wide_wide_cell_type_agnostic)
column_names_wide_wide_cell_type_agnostic

[1] 23766

    [1] "sample_id"      "A1BG"           "A1BG.AS1"       "A1CF"
    [5] "A2M"            "A2M.AS1"        "A2ML1"          "A2ML1.AS1"
    [9] "A3GALT2"        "A4GALT"         "AAAS"           "AACS"
   [13] "AADACL2.AS1"    "AAGAB"          "AAK1"           "AAMDC"
   [17] "AAMP"           "AANAT"          "AAR2"           "AARD"
   [21] "AARS"           "AARS2"          "AARSD1"         "AASDH"
   [25] "AASDHPPT"       "AASS"           "AATBC"          "AATF"
   [29] "AATK"           "ABALON"         "ABAT"           "ABCA1"
   [33] "ABCA10"         "ABCA12"         "ABCA13"         "ABCA2"
   [37] "ABCA3"          "ABCA4"          "ABCA5"          "ABCA6"
   [41] "ABCA7"          "ABCA8"          "ABCA9"          "ABCA9.AS1"
   [45] "ABCB1"          "ABCB10"         "ABCB11"         "ABCB4"
   [49] "ABCB5"          "ABCB6"          "ABCB7"          "ABCB8"
   [53] "ABCB9"          "ABCC1"          "ABCC10"         "ABCC11"
   [57] "ABCC2"          "ABCC3"          "ABCC4"          "ABCC5"
   [61] "ABCC5.AS1"      "ABCC6"          "ABCC8"          "ABCC9"
   [65] "ABCD1"          "ABCD2"          "ABCD3"          "ABCD4"
   [69] "ABCE1"          "ABCF1"          "ABCF2"          "ABCF3"
   [73] "ABCG1"          "ABCG2"          "ABCG5"          "ABCG8"
   [77] "ABHD1"          "ABHD10"         "ABHD11"         "ABHD12"
   [81] "ABHD12B"        "ABHD13"         "ABHD14A"        "ABHD14B"
   [85] "ABHD15"         "ABHD15.AS1"     "ABHD16A"        "ABHD17A"
   [89] "ABHD17B"        "ABHD17C"        "ABHD18"         "ABHD2"
   [93] "ABHD3"          "ABHD4"          "ABHD5"          "ABHD6"
   [97] "ABHD8"          "ABI1"           "ABI2"           "ABI3"
  [101] "ABI3BP"         "ABITRAM"        "ABL1"           "ABL2"
  [105] "ABLIM1"         "ABLIM2"         "ABLIM3"         "ABO"
  [109] "ABR"            "ABRA"           "ABRACL"         "ABRAXAS1"
  [113] "ABRAXAS2"       "ABT1"           "ABTB1"          "ABTB2"
  [117] "AC000032.1"     "AC000065.1"     "AC000065.2"     "AC000068.1"
  [121] "AC000085.1"     "AC000403.1"     "AC001226.1"     "AC002059.1"
  [125] "AC002064.1"     "AC002066.1"     "AC002069.2"     "AC002070.1"
  [129] "AC002072.1"     "AC002074.1"     "AC002091.1"     "AC002091.2"
  [133] "AC002094.4"     "AC002101.1"     "AC002115.1"     "AC002116.2"
  [137] "AC002128.1"     "AC002128.2"     "AC002306.1"     "AC002310.1"
  [141] "AC002310.2"     "AC002331.1"     "AC002377.1"     "AC002378.1"
  [145] "AC002383.1"     "AC002398.1"     "AC002401.1"     "AC002407.1"
  [149] "AC002429.2"     "AC002451.1"     "AC002454.1"     "AC002456.1"
  [153] "AC002460.2"     "AC002463.1"     "AC002467.1"     "AC002470.1"
  [157] "AC002472.1"     "AC002480.1"     "AC002480.2"     "AC002546.1"
  [161] "AC002550.1"     "AC002553.1"     "AC002553.2"     "AC002558.2"
  [165] "AC002558.3"     "AC003005.2"     "AC003035.1"     "AC003035.2"
  [169] "AC003086.1"     "AC003092.1"     "AC003093.1"     "AC003101.2"
  [173] "AC003102.1"     "AC003666.1"     "AC003681.1"     "AC003682.1"
  [177] "AC003956.1"     "AC003965.1"     "AC003973.1"     "AC003991.1"
  [181] "AC003991.2"     "AC004034.1"     "AC004039.1"     "AC004052.1"
  [185] "AC004053.1"     "AC004054.1"     "AC004067.1"     "AC004069.1"
  [189] "AC004076.2"     "AC004083.1"     "AC004112.1"     "AC004130.2"
  [193] "AC004148.1"     "AC004156.1"     "AC004158.1"     "AC004160.1"
  [197] "AC004223.2"     "AC004223.4"     "AC004231.1"     "AC004233.1"
  [201] "AC004233.3"     "AC004241.1"     "AC004241.3"     "AC004253.1"
  [205] "AC004257.1"     "AC004263.2"     "AC004381.1"     "AC004448.2"
  [209] "AC004466.1"     "AC004471.1"     "AC004477.1"     "AC004485.1"
  [213] "AC004492.1"     "AC004494.1"     "AC004522.3"     "AC004522.5"
  [217] "AC004528.1"     "AC004540.1"     "AC004540.2"     "AC004542.2"
  [221] "AC004551.1"     "AC004554.2"     "AC004556.3"     "AC004584.3"
  [225] "AC004585.1"     "AC004593.1"     "AC004593.2"     "AC004593.3"
  [229] "AC004594.1"     "AC004596.1"     "AC004672.1"     "AC004687.1"
  [233] "AC004690.2"     "AC004702.1"     "AC004704.1"     "AC004706.1"
  [237] "AC004706.3"     "AC004765.1"     "AC004771.1"     "AC004771.3"
  [241] "AC004771.4"     "AC004784.1"     "AC004797.1"     "AC004801.3"
  [245] "AC004801.4"     "AC004801.6"     "AC004803.1"     "AC004812.2"
  [249] "AC004816.1"     "AC004817.3"     "AC004817.5"     "AC004825.2"
  [253] "AC004825.3"     "AC004830.2"     "AC004832.1"     "AC004832.4"
  [257] "AC004832.6"     "AC004834.1"     "AC004837.2"     "AC004837.4"
  [261] "AC004839.2"     "AC004846.1"     "AC004846.2"     "AC004847.1"
  [265] "AC004854.2"     "AC004865.2"     "AC004884.2"     "AC004889.1"
  [269] "AC004893.3"     "AC004895.1"     "AC004900.1"     "AC004906.1"
  [273] "AC004908.2"     "AC004917.1"     "AC004918.1"     "AC004918.4"
  [277] "AC004921.1"     "AC004923.4"     "AC004938.2"     "AC004943.2"
  [281] "AC004947.3"     "AC004949.1"     "AC004951.1"     "AC004974.1"
  [285] "AC004982.2"     "AC004988.1"     "AC004990.1"     "AC005005.4"
  [289] "AC005009.2"     "AC005014.2"     "AC005014.4"     "AC005034.5"
  [293] "AC005034.6"     "AC005037.1"     "AC005041.4"     "AC005041.5"
  [297] "AC005050.3"     "AC005052.2"     "AC005062.1"     "AC005064.1"
  [301] "AC005070.3"     "AC005071.1"     "AC005072.1"     "AC005076.1"
  [305] "AC005081.1"     "AC005082.1"     "AC005082.2"     "AC005083.1"
  [309] "AC005091.1"     "AC005100.2"     "AC005104.3"     "AC005154.4"
  [313] "AC005162.1"     "AC005162.3"     "AC005165.1"     "AC005197.1"
  [317] "AC005208.1"     "AC005224.2"     "AC005224.3"     "AC005225.2"
  [321] "AC005225.3"     "AC005229.4"     "AC005229.5"     "AC005234.2"
  [325] "AC005237.1"     "AC005253.1"     "AC005261.1"     "AC005261.2"
  [329] "AC005264.1"     "AC005280.1"     "AC005280.2"     "AC005288.1"
  [333] "AC005304.3"     "AC005306.1"     "AC005323.1"     "AC005329.1"
  [337] "AC005332.1"     "AC005332.2"     "AC005332.3"     "AC005332.4"
  [341] "AC005332.5"     "AC005332.6"     "AC005332.7"     "AC005339.1"
  [345] "AC005342.2"     "AC005343.1"     "AC005343.4"     "AC005355.1"
  [349] "AC005363.2"     "AC005381.1"     "AC005387.2"     "AC005392.2"
  [353] "AC005400.1"     "AC005410.2"     "AC005476.2"     "AC005480.1"
  [357] "AC005481.1"     "AC005487.1"     "AC005498.2"     "AC005498.3"
  [361] "AC005520.2"     "AC005520.3"     "AC005520.5"     "AC005522.1"
  [365] "AC005523.1"     "AC005523.2"     "AC005532.1"     "AC005534.1"
  [369] "AC005537.1"     "AC005540.1"     "AC005562.1"     "AC005580.1"
  [373] "AC005586.1"     "AC005599.1"     "AC005614.1"     "AC005616.1"
  [377] "AC005618.1"     "AC005618.4"     "AC005632.3"     "AC005632.6"
  [381] "AC005670.1"     "AC005670.3"     "AC005674.2"     "AC005682.2"
  [385] "AC005695.2"     "AC005695.3"     "AC005696.1"     "AC005696.2"
  [389] "AC005696.4"     "AC005697.2"     "AC005699.1"     "AC005703.4"
  [393] "AC005726.1"     "AC005726.3"     "AC005726.4"     "AC005726.5"
  [397] "AC005736.1"     "AC005740.3"     "AC005740.5"     "AC005746.2"
  [401] "AC005759.1"     "AC005775.1"     "AC005776.2"     "AC005785.1"
  [405] "AC005786.2"     "AC005786.3"     "AC005803.1"     "AC005808.1"
  [409] "AC005821.1"     "AC005828.1"     "AC005828.3"     "AC005833.2"
  [413] "AC005837.1"     "AC005838.2"     "AC005840.2"     "AC005840.4"
  [417] "AC005842.1"     "AC005856.1"     "AC005871.2"     "AC005884.1"
  [421] "AC005899.1"     "AC005899.5"     "AC005899.6"     "AC005899.7"
  [425] "AC005899.8"     "AC005906.2"     "AC005911.1"     "AC005914.1"
  [429] "AC005920.1"     "AC005920.2"     "AC005921.2"     "AC005921.4"
  [433] "AC005944.1"     "AC005962.2"     "AC005972.3"     "AC005993.1"
  [437] "AC005998.1"     "AC005999.2"     "AC006001.2"     "AC006008.1"
  [441] "AC006017.1"     "AC006027.1"     "AC006033.2"     "AC006040.1"
  [445] "AC006042.2"     "AC006042.4"     "AC006059.1"     "AC006059.5"
  [449] "AC006064.1"     "AC006064.2"     "AC006064.3"     "AC006064.4"
  [453] "AC006064.5"     "AC006076.1"     "AC006111.2"     "AC006115.2"
  [457] "AC006116.8"     "AC006130.1"     "AC006141.1"     "AC006148.1"
  [461] "AC006157.1"     "AC006160.1"     "AC006197.2"     "AC006206.2"
  [465] "AC006207.1"     "AC006213.1"     "AC006213.2"     "AC006213.3"
  [469] "AC006230.1"     "AC006237.1"     "AC006238.1"     "AC006252.1"
  [473] "AC006270.1"     "AC006288.1"     "AC006296.3"     "AC006299.1"
  [477] "AC006305.1"     "AC006329.1"     "AC006333.1"     "AC006333.2"
  [481] "AC006348.1"     "AC006364.1"     "AC006369.1"     "AC006369.2"
  [485] "AC006372.1"     "AC006372.3"     "AC006378.1"     "AC006387.1"
  [489] "AC006427.2"     "AC006435.2"     "AC006441.1"     "AC006441.3"
  [493] "AC006445.3"     "AC006449.2"     "AC006449.3"     "AC006449.6"
  [497] "AC006452.1"     "AC006460.1"     "AC006460.2"     "AC006480.2"
  [501] "AC006483.2"     "AC006487.1"     "AC006504.1"     "AC006504.2"
  [505] "AC006504.5"     "AC006511.4"     "AC006511.6"     "AC006517.2"
  [509] "AC006525.1"     "AC006538.1"     "AC006547.1"     "AC006547.3"
  [513] "AC006581.1"     "AC006581.2"     "AC006942.1"     "AC006946.2"
  [517] "AC006960.2"     "AC006972.1"     "AC006974.2"     "AC006994.2"
  [521] "AC007001.1"     "AC007014.1"     "AC007029.1"     "AC007032.1"
  [525] "AC007036.1"     "AC007036.2"     "AC007036.3"     "AC007036.5"
  [529] "AC007038.1"     "AC007038.2"     "AC007040.1"     "AC007066.2"
  [533] "AC007066.3"     "AC007091.1"     "AC007098.1"     "AC007099.1"
  [537] "AC007100.1"     "AC007114.1"     "AC007114.2"     "AC007130.1"
  [541] "AC007163.1"     "AC007179.1"     "AC007182.1"     "AC007192.2"
  [545] "AC007193.1"     "AC007216.1"     "AC007216.2"     "AC007216.3"
  [549] "AC007216.4"     "AC007218.3"     "AC007220.1"     "AC007220.2"
  [553] "AC007240.3"     "AC007255.1"     "AC007262.2"     "AC007271.1"
  [557] "AC007277.1"     "AC007278.1"     "AC007278.2"     "AC007279.2"
  [561] "AC007285.1"     "AC007285.2"     "AC007292.1"     "AC007292.2"
  [565] "AC007292.3"     "AC007298.1"     "AC007298.2"     "AC007314.1"
  [569] "AC007319.1"     "AC007325.4"     "AC007327.2"     "AC007336.1"
  [573] "AC007342.1"     "AC007342.4"     "AC007342.5"     "AC007344.1"
  [577] "AC007347.1"     "AC007349.1"     "AC007349.2"     "AC007349.3"
  [581] "AC007364.1"     "AC007365.1"     "AC007368.1"     "AC007370.2"
  [585] "AC007376.2"     "AC007381.1"     "AC007383.2"     "AC007383.3"
  [589] "AC007384.1"     "AC007387.2"     "AC007387.3"     "AC007389.1"
  [593] "AC007390.2"     "AC007391.1"     "AC007391.2"     "AC007402.1"
  [597] "AC007405.1"     "AC007405.3"     "AC007406.5"     "AC007448.4"
  [601] "AC007448.5"     "AC007450.1"     "AC007493.1"     "AC007493.2"
  [605] "AC007494.2"     "AC007496.2"     "AC007513.1"     "AC007529.2"
  [609] "AC007533.1"     "AC007541.1"     "AC007546.1"     "AC007563.2"
  [613] "AC007566.1"     "AC007569.1"     "AC007570.1"     "AC007598.2"
  [617] "AC007599.2"     "AC007601.1"     "AC007608.1"     "AC007608.2"
  [621] "AC007608.3"     "AC007610.1"     "AC007610.2"     "AC007610.5"
  [625] "AC007611.1"     "AC007613.1"     "AC007619.1"     "AC007620.2"
  [629] "AC007622.2"     "AC007637.1"     "AC007656.2"     "AC007663.3"
  [633] "AC007666.1"     "AC007666.2"     "AC007679.1"     "AC007681.1"
  [637] "AC007686.2"     "AC007686.3"     "AC007686.4"     "AC007695.1"
  [641] "AC007728.1"     "AC007728.2"     "AC007731.3"     "AC007773.1"
  [645] "AC007780.1"     "AC007785.1"     "AC007785.3"     "AC007786.1"
  [649] "AC007823.1"     "AC007834.1"     "AC007846.1"     "AC007877.1"
  [653] "AC007878.1"     "AC007879.3"     "AC007880.1"     "AC007881.2"
  [657] "AC007881.3"     "AC007881.4"     "AC007923.4"     "AC007938.2"
  [661] "AC007950.1"     "AC007950.2"     "AC007952.2"     "AC007952.4"
  [665] "AC007991.3"     "AC007993.3"     "AC007998.3"     "AC007998.4"
  [669] "AC008014.1"     "AC008026.3"     "AC008033.3"     "AC008035.1"
  [673] "AC008040.1"     "AC008050.1"     "AC008063.1"     "AC008067.1"
  [677] "AC008073.1"     "AC008074.2"     "AC008079.1"     "AC008080.3"
  [681] "AC008083.2"     "AC008083.3"     "AC008083.4"     "AC008105.1"
  [685] "AC008105.3"     "AC008114.1"     "AC008115.1"     "AC008115.2"
  [689] "AC008115.3"     "AC008115.4"     "AC008119.1"     "AC008124.1"
  [693] "AC008127.1"     "AC008147.1"     "AC008147.2"     "AC008149.1"
  [697] "AC008149.2"     "AC008264.2"     "AC008267.5"     "AC008269.1"
  [701] "AC008273.1"     "AC008277.1"     "AC008280.3"     "AC008378.1"
  [705] "AC008393.1"     "AC008397.1"     "AC008403.2"     "AC008403.3"
  [709] "AC008415.1"     "AC008429.1"     "AC008429.3"     "AC008438.1"
  [713] "AC008438.2"     "AC008440.1"     "AC008440.2"     "AC008443.1"
  [717] "AC008443.4"     "AC008443.5"     "AC008443.6"     "AC008443.8"
  [721] "AC008443.9"     "AC008462.1"     "AC008467.1"     "AC008474.1"
  [725] "AC008494.3"     "AC008496.2"     "AC008507.2"     "AC008507.4"
  [729] "AC008507.5"     "AC008522.1"     "AC008525.1"     "AC008532.1"
  [733] "AC008534.1"     "AC008537.2"     "AC008537.4"     "AC008543.1"
  [737] "AC008543.5"     "AC008549.2"     "AC008551.1"     "AC008554.1"
  [741] "AC008555.2"     "AC008555.4"     "AC008568.1"     "AC008569.1"
  [745] "AC008569.2"     "AC008571.2"     "AC008572.1"     "AC008574.1"
  [749] "AC008581.1"     "AC008591.1"     "AC008592.1"     "AC008592.2"
  [753] "AC008592.4"     "AC008608.2"     "AC008610.1"     "AC008619.1"
  [757] "AC008622.2"     "AC008629.1"     "AC008649.1"     "AC008649.2"
  [761] "AC008655.2"     "AC008662.1"     "AC008667.1"     "AC008667.3"
  [765] "AC008676.1"     "AC008679.1"     "AC008680.1"     "AC008686.1"
  [769] "AC008691.1"     "AC008696.2"     "AC008728.1"     "AC008731.1"
  [773] "AC008734.2"     "AC008735.1"     "AC008735.2"     "AC008735.3"
  [777] "AC008736.1"     "AC008738.1"     "AC008738.3"     "AC008747.1"
  [781] "AC008750.2"     "AC008750.4"     "AC008750.7"     "AC008751.3"
  [785] "AC008752.1"     "AC008752.2"     "AC008753.3"     "AC008758.2"
  [789] "AC008761.1"     "AC008763.1"     "AC008764.2"     "AC008764.6"
  [793] "AC008764.7"     "AC008764.8"     "AC008770.3"     "AC008771.1"
  [797] "AC008781.1"     "AC008781.2"     "AC008825.1"     "AC008840.1"
  [801] "AC008870.2"     "AC008870.4"     "AC008871.1"     "AC008875.1"
  [805] "AC008875.2"     "AC008875.3"     "AC008883.1"     "AC008883.3"
  [809] "AC008892.1"     "AC008894.2"     "AC008897.2"     "AC008906.1"
  [813] "AC008906.2"     "AC008914.1"     "AC008915.1"     "AC008915.2"
  [817] "AC008937.1"     "AC008937.2"     "AC008937.3"     "AC008945.2"
  [821] "AC008946.1"     "AC008957.1"     "AC008957.2"     "AC008964.1"
  [825] "AC008966.1"     "AC008966.3"     "AC008969.1"     "AC008972.2"
  [829] "AC008982.2"     "AC009005.1"     "AC009019.1"     "AC009019.2"
  [833] "AC009021.1"     "AC009032.1"     "AC009041.1"     "AC009041.2"
  [837] "AC009041.4"     "AC009053.2"     "AC009053.3"     "AC009054.2"
  [841] "AC009055.1"     "AC009060.1"     "AC009061.2"     "AC009063.2"
  [845] "AC009065.2"     "AC009065.4"     "AC009065.8"     "AC009081.2"
  [849] "AC009088.1"     "AC009090.1"     "AC009090.3"     "AC009090.6"
  [853] "AC009093.1"     "AC009093.2"     "AC009093.4"     "AC009093.5"
  [857] "AC009093.6"     "AC009097.1"     "AC009107.1"     "AC009107.2"
  [861] "AC009113.1"     "AC009118.2"     "AC009118.3"     "AC009119.1"
  [865] "AC009120.2"     "AC009120.3"     "AC009120.4"     "AC009120.5"
  [869] "AC009121.3"     "AC009123.1"     "AC009126.1"     "AC009133.1"
  [873] "AC009133.2"     "AC009133.3"     "AC009133.4"     "AC009137.1"
  [877] "AC009139.2"     "AC009141.1"     "AC009145.3"     "AC009148.1"
  [881] "AC009152.1"     "AC009152.3"     "AC009152.6"     "AC009163.1"
  [885] "AC009163.7"     "AC009171.2"     "AC009185.1"     "AC009226.1"
  [889] "AC009228.1"     "AC009229.2"     "AC009237.14"    "AC009242.1"
  [893] "AC009244.2"     "AC009264.1"     "AC009269.2"     "AC009271.1"
  [897] "AC009275.1"     "AC009276.1"     "AC009283.1"     "AC009292.1"
  [901] "AC009292.2"     "AC009299.3"     "AC009303.2"     "AC009309.1"
  [905] "AC009312.1"     "AC009313.1"     "AC009315.1"     "AC009318.1"
  [909] "AC009318.2"     "AC009318.3"     "AC009318.4"     "AC009365.1"
  [913] "AC009365.4"     "AC009387.1"     "AC009403.1"     "AC009403.2"
  [917] "AC009404.1"     "AC009411.2"     "AC009432.2"     "AC009435.1"
  [921] "AC009478.1"     "AC009480.1"     "AC009486.2"     "AC009495.1"
  [925] "AC009495.3"     "AC009501.3"     "AC009505.1"     "AC009506.1"
  [929] "AC009509.1"     "AC009522.1"     "AC009542.1"     "AC009549.1"
  [933] "AC009554.1"     "AC009560.1"     "AC009560.3"     "AC009560.4"
  [937] "AC009562.1"     "AC009563.1"     "AC009570.1"     "AC009570.2"
  [941] "AC009630.1"     "AC009630.2"     "AC009630.3"     "AC009630.4"
  [945] "AC009682.1"     "AC009686.1"     "AC009686.2"     "AC009690.2"
  [949] "AC009704.2"     "AC009716.1"     "AC009754.1"     "AC009754.2"
  [953] "AC009779.2"     "AC009779.5"     "AC009802.1"     "AC009812.1"
  [957] "AC009812.3"     "AC009812.4"     "AC009831.1"     "AC009831.3"
  [961] "AC009879.4"     "AC009902.2"     "AC009908.1"     "AC009948.2"
  [965] "AC009948.3"     "AC009950.1"     "AC009951.5"     "AC009951.6"
  [969] "AC009961.1"     "AC009961.4"     "AC009962.1"     "AC009971.1"
  [973] "AC009974.1"     "AC009974.2"     "AC009975.1"     "AC009975.2"
  [977] "AC009996.1"     "AC010082.1"     "AC010092.1"     "AC010145.1"
  [981] "AC010148.1"     "AC010149.1"     "AC010168.1"     "AC010168.2"
  [985] "AC010173.1"     "AC010175.1"     "AC010186.1"     "AC010186.3"
  [989] "AC010197.1"     "AC010198.1"     "AC010198.2"     "AC010201.3"
  [993] "AC010203.2"     "AC010205.1"     "AC010210.1"     "AC010226.1"
  [997] "AC010230.1"     "AC010240.3"     "AC010245.1"     "AC010245.2"
 [1001] "AC010247.1"     "AC010247.2"     "AC010255.1"     "AC010255.3"
 [1005] "AC010260.1"     "AC010261.2"     "AC010271.2"     "AC010273.2"
 [1009] "AC010273.3"     "AC010275.1"     "AC010280.2"     "AC010285.3"
 [1013] "AC010300.1"     "AC010319.3"     "AC010319.4"     "AC010320.1"
 [1017] "AC010320.2"     "AC010320.3"     "AC010320.4"     "AC010325.1"
 [1021] "AC010326.3"     "AC010327.4"     "AC010327.5"     "AC010327.7"
 [1025] "AC010327.8"     "AC010331.1"     "AC010332.3"     "AC010333.2"
 [1029] "AC010336.1"     "AC010336.6"     "AC010336.8"     "AC010343.3"
 [1033] "AC010359.2"     "AC010359.3"     "AC010422.1"     "AC010422.2"
 [1037] "AC010442.1"     "AC010468.2"     "AC010476.2"     "AC010487.2"
 [1041] "AC010491.1"     "AC010491.2"     "AC010501.2"     "AC010503.4"
 [1045] "AC010504.1"     "AC010519.1"     "AC010528.1"     "AC010530.1"
 [1049] "AC010531.3"     "AC010531.5"     "AC010531.6"     "AC010536.1"
 [1053] "AC010536.3"     "AC010538.1"     "AC010542.2"     "AC010542.4"
 [1057] "AC010542.5"     "AC010547.1"     "AC010601.1"     "AC010609.1"
 [1061] "AC010615.2"     "AC010618.2"     "AC010618.3"     "AC010623.1"
 [1065] "AC010624.1"     "AC010624.3"     "AC010624.5"     "AC010632.1"
 [1069] "AC010632.2"     "AC010642.2"     "AC010643.1"     "AC010649.1"
 [1073] "AC010654.1"     "AC010677.2"     "AC010680.1"     "AC010680.2"
 [1077] "AC010680.3"     "AC010680.4"     "AC010680.5"     "AC010727.1"
 [1081] "AC010735.2"     "AC010746.2"     "AC010754.1"     "AC010761.1"
 [1085] "AC010761.2"     "AC010761.3"     "AC010789.1"     "AC010789.2"
 [1089] "AC010809.1"     "AC010809.2"     "AC010809.3"     "AC010834.2"
 [1093] "AC010864.1"     "AC010883.1"     "AC010883.2"     "AC010883.3"
 [1097] "AC010884.1"     "AC010889.1"     "AC010889.2"     "AC010894.2"
 [1101] "AC010894.3"     "AC010894.4"     "AC010896.1"     "AC010913.1"
 [1105] "AC010967.1"     "AC010969.2"     "AC010969.3"     "AC010976.1"
 [1109] "AC010978.1"     "AC010983.1"     "AC010996.1"     "AC010997.3"
 [1113] "AC010998.1"     "AC010999.2"     "AC011008.1"     "AC011029.1"

In [8]:
common_genes = intersect(column_names_wide_bulkseq, column_names_wide_wide_cell_type_agnostic)

In [9]:
length(common_genes)

[1] 14739

In [10]:
data <- read.csv("/ictstr01/home/icb/bhavishya.nelakuditi/mofa_workflow/results/03_results/03_Weight_Data_CGS_v3_MOFA.csv")

# Extract gene names after the double underscore
gene_names <- sapply(data$variable_name, function(x) {
  # Split by double underscore and take the second part
  parts <- strsplit(x, "__")[[1]]
  if(length(parts) > 1) {
    gene <- parts[2]
    # Remove version numbers (anything after a period)
    gene <- sub("\\.\\d+$", "", gene)
    return(gene)
  } else {
    return(NA)  # Return NA if no double underscore is found
  }
})

# Create a new data frame with the original variable names and the extracted gene names
result <- data.frame(
  original_name = data$variable_name,
  gene_name = gene_names,
  Factor3 = data$Factor3  
)


# Display the first few rows of the result
head(result)

                              original_name                 gene_name
Activated.T.cells__AAK1       Activated.T.cells__AAK1       AAK1
Activated.T.cells__ABLIM1     Activated.T.cells__ABLIM1     ABLIM1
Activated.T.cells__AC007952.4 Activated.T.cells__AC007952.4 AC007952
Activated.T.cells__AC016831.7 Activated.T.cells__AC016831.7 AC016831
Activated.T.cells__AC022217.3 Activated.T.cells__AC022217.3 AC022217
Activated.T.cells__AC023424.3 Activated.T.cells__AC023424.3 AC023424
                              Factor3
Activated.T.cells__AAK1        0.06532119
Activated.T.cells__ABLIM1      0.35685062
Activated.T.cells__AC007952.4 -0.47819405
Activated.T.cells__AC016831.7 -0.17591274
Activated.T.cells__AC022217.3 -0.46738407
Activated.T.cells__AC023424.3 -0.52896990

In [11]:
gene_df = result

In [12]:

# First, filter out genes whose rownames start with "proteomic" or "clinical"
filtered_df <- gene_df[!grepl("^proteomic|^clinical", rownames(gene_df)), ]

# Sort by Factor3 in descending order to get highest positive values
top_positive <- filtered_df[order(filtered_df$Factor3, decreasing = TRUE), ]
# Take the top 250
top_positive_250 <- head(top_positive, 250)

# Sort by Factor3 in ascending order to get highest negative values
top_negative <- filtered_df[order(filtered_df$Factor3, decreasing = FALSE), ]
# Take the top 250
top_negative_250 <- head(top_negative, 250)

# Combine the two sets to get the top 500
top_500_genes <- rbind(top_positive_250, top_negative_250)

In [13]:
top_500_genes

                                 original_name                    gene_name
Classical.Monocytes__NLRP3       Classical.Monocytes__NLRP3       NLRP3
Classical.Monocytes__AP1S2       Classical.Monocytes__AP1S2       AP1S2
Classical.Monocytes__LINC01588   Classical.Monocytes__LINC01588   LINC01588
Classical.Monocytes__PNRC1       Classical.Monocytes__PNRC1       PNRC1
Classical.Monocytes__SERPINB9    Classical.Monocytes__SERPINB9    SERPINB9
Classical.Monocytes__SEPTIN4.AS1 Classical.Monocytes__SEPTIN4.AS1 SEPTIN4.AS1
Classical.Monocytes__IL1B        Classical.Monocytes__IL1B        IL1B
Classical.Monocytes__NFKBIZ      Classical.Monocytes__NFKBIZ      NFKBIZ
Activated.T.cells__FTH1          Activated.T.cells__FTH1          FTH1
Classical.Monocytes__FLNA        Classical.Monocytes__FLNA        FLNA
Classical.Monocytes__TMEM107     Classical.Monocytes__TMEM107     TMEM107
Classical.Monocytes__RNF19B      Classical.Monocytes__RNF19B      RNF19B
Classical.Monocytes__PFKFB3      Classical.Monocytes__PFKFB3      PFKFB3
Classical.Monocytes__IER3        Classical.Monocytes__IER3        IER3
Classical.Monocytes__PMAIP1      Classical.Monocytes__PMAIP1      PMAIP1
Classical.Monocytes__PLAUR       Classical.Monocytes__PLAUR       PLAUR
Classical.Monocytes__LCP2        Classical.Monocytes__LCP2        LCP2
Classical.Monocytes__OLR1        Classical.Monocytes__OLR1        OLR1
Classical.Monocytes__NFKB1       Classical.Monocytes__NFKB1       NFKB1
Classical.Monocytes__GCH1        Classical.Monocytes__GCH1        GCH1
Classical.Monocytes__AZIN1.AS1   Classical.Monocytes__AZIN1.AS1   AZIN1.AS1
Classical.Monocytes__NFKBIA      Classical.Monocytes__NFKBIA      NFKBIA
Classical.Monocytes__MAP3K8      Classical.Monocytes__MAP3K8      MAP3K8
Classical.Monocytes__GPR132      Classical.Monocytes__GPR132      GPR132
Classical.Monocytes__OGFRL1      Classical.Monocytes__OGFRL1      OGFRL1
Classical.Monocytes__AQP9        Classical.Monocytes__AQP9        AQP9
Classical.Monocytes__STX11       Classical.Monocytes__STX11       STX11
Classical.Monocytes__CCL3        Classical.Monocytes__CCL3        CCL3
Classical.Monocytes__IRAK2       Classical.Monocytes__IRAK2       IRAK2
Classical.Monocytes__CCL4L2      Classical.Monocytes__CCL4L2      CCL4L2
⋮                                ⋮                                ⋮
Classical.Monocytes__PLXDC2      Classical.Monocytes__PLXDC2      PLXDC2
Activated.T.cells__HIVEP2        Activated.T.cells__HIVEP2        HIVEP2
Activated.T.cells__RFX3          Activated.T.cells__RFX3          RFX3
Classical.Monocytes__ADAM10      Classical.Monocytes__ADAM10      ADAM10
Activated.T.cells__DENND4A       Activated.T.cells__DENND4A       DENND4A
T.cells__ITK                     T.cells__ITK                     ITK
Classical.Monocytes__SLC8A1      Classical.Monocytes__SLC8A1      SLC8A1
Classical.Monocytes__ATP11A      Classical.Monocytes__ATP11A      ATP11A
Classical.Monocytes__DYNC1H1     Classical.Monocytes__DYNC1H1     DYNC1H1
Regulatory.T.cells__NFE2L3       Regulatory.T.cells__NFE2L3       NFE2L3
Activated.T.cells__PLCL1         Activated.T.cells__PLCL1         PLCL1
Activated.T.cells__YME1L1        Activated.T.cells__YME1L1        YME1L1
Regulatory.T.cells__ATF7IP       Regulatory.T.cells__ATF7IP       ATF7IP
Activated.T.cells__CUL3          Activated.T.cells__CUL3          CUL3
Classical.Monocytes__AFTPH       Classical.Monocytes__AFTPH       AFTPH
Classical.Monocytes__C5AR1       Classical.Monocytes__C5AR1       C5AR1
Classical.Monocytes__HNRNPU      Classical.Monocytes__HNRNPU      HNRNPU
Dendritic.cells__FBXO32          Dendritic.cells__FBXO32          FBXO32
Classical.Monocytes__TAOK1       Classical.Monocytes__TAOK1       TAOK1
T.cells__SERBP1                  T.cells__SERBP1                  SERBP1
Classical.Monocytes__ASH1L       Classical.Monocytes__ASH1L       ASH1L
Classical.Monocytes__SMG7        Classical.Monocytes__SMG7        SMG7
Dendritic.cells__IGF1R           Dendritic.cells__IGF1R           IGF1R
Classical.Monocytes__FKBP5       Classical.Monocytes__FKBP5       FKBP5
Classical.Monocytes__H2AFJ       Classical.Monocytes__H2AFJ       H2AFJ
Classical.Monocytes__PRKCB       Classical.Monocytes__PRKCB       PRKCB
Activated.T.cells__PDE3B         Activated.T.cells__PDE3B         PDE3B
Activated.T.cells__LINC01619     Activated.T.cells__LINC01619     LINC01619
Classical.Monocytes__ADIPOR2     Classical.Monocytes__ADIPOR2     ADIPOR2
B.Cells__SNHG12                  B.Cells__SNHG12                  SNHG12
                                 Factor3
Classical.Monocytes__NLRP3       0.8120541
Classical.Monocytes__AP1S2       0.8114625
Classical.Monocytes__LINC01588   0.7734370
Classical.Monocytes__PNRC1       0.7632843
Classical.Monocytes__SERPINB9    0.7535938
Classical.Monocytes__SEPTIN4.AS1 0.7506818
Classical.Monocytes__IL1B        0.7428163
Classical.Monocytes__NFKBIZ      0.7397043
Activated.T.cells__FTH1          0.7382639
Classical.Monocytes__FLNA        0.7338577
Classical.Monocytes__TMEM107     0.7256048
Classical.Monocytes__RNF19B      0.7211159
Classical.Monocytes__PFKFB3      0.7147683
Classical.Monocytes__IER3        0.7061324
Classical.Monocytes__PMAIP1      0.7049417
Classical.Monocytes__PLAUR       0.7024896
Classical.Monocytes__LCP2        0.6997937
Classical.Monocytes__OLR1        0.6967453
Classical.Monocytes__NFKB1       0.6964618
Classical.Monocytes__GCH1        0.6952036
Classical.Monocytes__AZIN1.AS1   0.6915530
Classical.Monocytes__NFKBIA      0.6913323
Classical.Monocytes__MAP3K8      0.6884514
Classical.Monocytes__GPR132      0.6858832
Classical.Monocytes__OGFRL1      0.6848860
Classical.Monocytes__AQP9        0.6844678
Classical.Monocytes__STX11       0.6783202
Classical.Monocytes__CCL3        0.6764950
Classical.Monocytes__IRAK2       0.6730902
Classical.Monocytes__CCL4L2      0.6716159
⋮                                ⋮
Classical.Monocytes__PLXDC2      -0.3834012
Activated.T.cells__HIVEP2        -0.3821965
Activated.T.cells__RFX3          -0.3816990
Classical.Monocytes__ADAM10      -0.3816239
Activated.T.cells__DENND4A       -0.3813406
T.cells__ITK                     -0.3812878
Classical.Monocytes__SLC8A1      -0.3796658
Classical.Monocytes__ATP11A      -0.3793187
Classical.Monocytes__DYNC1H1     -0.3782216
Regulatory.T.cells__NFE2L3       -0.3781641
Activated.T.cells__PLCL1         -0.3779055
Activated.T.cells__YME1L1        -0.3771197
Regulatory.T.cells__ATF7IP       -0.3770153
Activated.T.cells__CUL3          -0.3768504
Classical.Monocytes__AFTPH       -0.3767746
Classical.Monocytes__C5AR1       -0.3764148
Classical.Monocytes__HNRNPU      -0.3763153
Dendritic.cells__FBXO32          -0.3754737
Classical.Monocytes__TAOK1       -0.3749169
T.cells__SERBP1                  -0.3748932
Classical.Monocytes__ASH1L       -0.3739844
Classical.Monocytes__SMG7        -0.3731834
Dendritic.cells__IGF1R           -0.3721792
Classical.Monocytes__FKBP5       -0.3721111
Classical.Monocytes__H2AFJ       -0.3718296
Classical.Monocytes__PRKCB       -0.3716359
Activated.T.cells__PDE3B         -0.3711816
Activated.T.cells__LINC01619     -0.3704000
Classical.Monocytes__ADIPOR2     -0.3691611
B.Cells__SNHG12                  -0.3681411

In [14]:
top_500_factor3_genes = unique(top_500_genes$gene_name)
top_500_factor3_genes

  [1] "NLRP3"        "AP1S2"        "LINC01588"    "PNRC1"        "SERPINB9"
  [6] "SEPTIN4.AS1"  "IL1B"         "NFKBIZ"       "FTH1"         "FLNA"
 [11] "TMEM107"      "RNF19B"       "PFKFB3"       "IER3"         "PMAIP1"
 [16] "PLAUR"        "LCP2"         "OLR1"         "NFKB1"        "GCH1"
 [21] "AZIN1.AS1"    "NFKBIA"       "MAP3K8"       "GPR132"       "OGFRL1"
 [26] "AQP9"         "STX11"        "CCL3"         "IRAK2"        "CCL4L2"
 [31] "CDKN1A"       "IFNGR2"       "TGFB1"        "DENND5A"      "ECE1"
 [36] "PILRA"        "S100A10"      "ICAM1"        "RNF125"       "ETS2"
 [41] "TNFAIP8"      "ANXA1"        "ADAMTSL4.AS1" "UBE2D1"       "TNF"
 [46] "ITGAV"        "BCL2A1"       "CCL3L1"       "ANXA5"        "TAGAP"
 [51] "TNFAIP2"      "Z93241"       "EIF4E"        "PTGER4"       "NFE2L2"
 [56] "P2RY8"        "PELI1"        "HLA.DPA1"     "MIR3945HG"    "IL10RA"
 [61] "STK10"        "MIR222HG"     "TNIP1"        "PLK3"         "BTG1"
 [66] "ZFP36L2"      "TOM1"         "SLC9A8"       "EHD1"         "CCNI"
 [71] "CD37"         "CHMP4B"       "LACTB"        "SH3BGRL3"     "PPT1"
 [76] "PPP2R5C"      "KDM6B"        "GNAI2"        "SEC11A"       "CCL4"
 [81] "LPXN"         "MAPK6"        "CXCL8"        "ITGAX"        "PTGS2"
 [86] "AHNAK"        "BASP1"        "CD44"         "NOCT"         "NINJ1"
 [91] "ZNF331"       "B3GNT5"       "GSTO1"        "ITGA5"        "ZNF267"
 [96] "MYH9"         "PTP4A2"       "TNFRSF1B"     "PHLDA1"       "AC012447"
[101] "DUSP2"        "HLA.DPB1"     "KMO"          "VOPP1"        "USP36"
[106] "NFAT5"        "TNFAIP3"      "FGR"          "CD58"         "USP3"
[111] "BID"          "AL021155"     "ARFGAP3"      "ELK3"         "MCL1"
[116] "NDUFS5"       "CITED2"       "ARHGAP31"     "PPP1R15A"     "ZFP36"
[121] "PIM3"         "SMS"          "CD302"        "CDC42EP3"     "MYOF"
[126] "DEK"          "CD83"         "FLOT1"        "SPOCK2"       "SRSF5"
[131] "PIK3R5"       "PDE4B"        "ALDH1A2"      "CAST"         "MSN"
[136] "SNX9"         "CXCL2"        "AZIN1"        "METRNL"       "CXCR4"
[141] "LMNA"         "TMSB4X"       "AREG"         "ARL4C"        "EVI2B"
[146] "LUCAT1"       "ADA2"         "UBE2J1"       "BTG2"         "B2M"
[151] "SNU13"        "KLF10"        "USP12"        "RIPK1"        "IL6R"
[156] "HNRNPUL1"     "SAMSN1"       "CCNH"         "HERPUD2"      "HMGB2"
[161] "JUND"         "NCOA4"        "TIPARP"       "CD96"         "BHLHE40"
[166] "TEX14"        "TSC22D3"      "VIM"          "SUSD6"        "CSF3R"
[171] "ITM2B"        "ABCA1"        "SLC7A5"       "B4GALT1"      "NACA"
[176] "ARL8B"        "COTL1"        "FNIP2"        "LINC00910"    "TPI1"
[181] "HLA.B"        "ADGRE2"       "HIGD2A"       "LSP1"         "LINC00513"
[186] "TUBA4A"       "LGALS3"       "CCL5"         "SOD2"         "SKIL"
[191] "FBXO33"       "DRAM1"        "ATP13A3"      "NCF2"         "MYO9B"
[196] "MARCKS"       "MANBA"        "H1FX"         "EIF2AK3"      "HADHA"
[201] "CARD16"       "RDX"          "RAPGEF1"      "ATP6AP2"      "KLF2"
[206] "LRRFIP1"      "KLF6"         "CLIC4"        "ERP29"        "MBP"
[211] "MIDN"         "ACSL1"        "UPP1"         "BCAS2"        "RASGEF1B"
[216] "HNRNPK"       "EIF1"         "NIBAN1"       "CIB1"         "PCBP1"
[221] "PPIF"         "OAZ1"         "C12orf57"     "SKP1"         "SLC12A2"
[226] "SIK3"         "MAN1A1"       "FGD4"         "HSPH1"        "LRRC23"
[231] "HSP90AA1"     "SCML4"        "USP32"        "CNOT2"        "HSPE1"
[236] "INTS6"        "HSPA1B"       "RLF"          "AL691403"     "MAPK14"
[241] "ANKRD17"      "TAOK3"        "ARIH1"        "ERO1B"        "SF3B5"
[246] "BZW2"         "EIF4A2"       "PPP1R10"      "DNAJB6"       "HECA"
[251] "RBM47"        "RB1"          "RIPOR2"       "NFE2L3"       "HSPA1A"
[256] "ARL4A"        "ATP6V1A"      "RSRP1"        "MAP3K2"       "MBNL1"
[261] "SETX"         "FBXW7"        "RGS2"         "RSRC2"        "BICRAL"
[266] "KCNE1"        "FRMD4B"       "YTHDF3"       "ZDHHC20"      "VAPA"
[271] "TAF4B"        "FUS"          "PICALM"       "TBXAS1"       "BTBD9"
[276] "AC023424"     "GADD45B"      "CREBRF"       "ITGA6"        "MORF4L2"
[281] "HMGCS1"       "UBE2W"        "SNHG12"       "NEU1"         "KLHL18"
[286] "GAS5"         "HEXA"         "CPEB4"        "PRCP"         "HSPD1"
[291] "PLK2"         "TFEC"         "PCSK5"        "RBM6"         "ZNF407"
[296] "GIMAP7"       "RAF1"         "AGO3"         "TRA2B"        "SBF2"
[301] "NOP58"        "TRA2A"        "ZC3HAV1"      "TLE4"         "FBXO32"
[306] "RALGAPA1"     "CBLB"         "INTS6L"       "HIPK3"        "ITK"
[311] "ARHGAP24"     "GLS"          "AC007952"     "KCNQ1OT1"     "XRN2"
[316] "FHIT"         "MIER1"        "SPPL3"        "HNRNPC"       "USP8"
[321] "EIF2S2"       "THUMPD3.AS1"  "CYSTM1"       "AC022217"     "DIAPH2"
[326] "BCL2"         "MARCH1"       "LEF1"         "GPBP1"        "BAZ2B"
[331] "GOLGB1"       "RFX2"         "AFF1"         "RAB11FIP1"    "AC010609"
[336] "EFCAB2"       "GATAD2B"      "MFSD1"        "H2AFX"        "ADAM9"
[341] "UAP1"         "ZSWIM6"       "ADGRE5"       "MAPRE2"       "HSPA8"
[346] "PBRM1"        "XPR1"         "SNHG29"       "PRKCA"        "VTI1A"
[351] "SMCHD1"       "TPM3"         "EDA"          "UVRAG"        "CROCC"
[356] "ABHD5"        "SPTLC2"       "GNAQ"         "SRSF3"        "GALM"
[361] "ATP8B4"       "DHX36"        "DNAJA1"       "BLOC1S6"      "IFRD1"
[366] "ACTG1"        "CCNL1"        "GADD45G"      "RAB8B"        "SLC16A10"
[371] "BRD2"         "KDM2A"        "PPP1R12A"     "FAM133B"      "JARID2"
[376] "DNAJB1"       "GLUL"         "WDFY2"        "POLG2"        "ST6GALNAC3"
[381] "MED29"        "MIR181A1HG"   "RILPL2"       "VMP1"         "ERC1"
[386] "HNRNPA2B1"    "FAR1"         "DCP1A"        "YWHAG"        "STAT3"
[391] "ANKHD1"       "DPYD"         "KANSL1"       "ZNF609"       "UBE2H"
[396] "ATF6"         "HIPK1"        "FOXO1"        "SNHG7"        "NR4A1"
[401] "C1QBP"        "PPP3R1"       "RSBN1"        "HNRNPH1"      "ZFAS1"
[406] "PCF11"        "CREB1"        "ARID5B"       "STT3B"        "BTBD7"
[411] "SRSF7"        "ATG3"         "CASP8"        "ARHGEF40"     "PLXDC2"
[416] "HIVEP2"       "RFX3"         "ADAM10"       "DENND4A"      "SLC8A1"
[421] "ATP11A"       "DYNC1H1"      "PLCL1"        "YME1L1"       "ATF7IP"
[426] "CUL3"         "AFTPH"        "C5AR1"        "HNRNPU"       "TAOK1"
[431] "SERBP1"       "ASH1L"        "SMG7"         "IGF1R"        "FKBP5"
[436] "H2AFJ"        "PRKCB"        "PDE3B"        "LINC01619"    "ADIPOR2"

In [15]:
top_500_factor3_genes = intersect(top_500_factor3_genes, colnames(wide_cell_type_agnostic))
length(top_500_factor3_genes)

[1] 432

In [16]:
top_500_factor3_genes_matrix = wide_cell_type_agnostic[, top_500_factor3_genes]
head(top_500_factor3_genes_matrix)

  NLRP3      AP1S2      LINC01588 PNRC1      SERPINB9   SEPTIN4.AS1 IL1B
1 0.49789692  0.2214497 0.5273679 -0.4544784  1.3238074 0.6503535   0.44019785
2 0.61874786  0.7840859 0.6187479  0.7494131 -0.5877486 0.7840859   0.19504103
3 0.22144974 -0.3016924 0.3839292  0.8752401  1.1566322 0.8197281   0.01292112
4 0.09056902 -0.6503535 0.7156187 -0.6344714  0.9743216 0.6187479   0.06464883
5 1.32380742  0.2480138 1.4598551  1.2641239  0.2747541 0.4688522   1.06106625
6 1.73650701  0.2747541 2.3148972  1.0386467  2.0411380 2.0411380   1.73650701
  NFKBIZ      FTH1       FLNA       ⋯ SERBP1     ASH1L      SMG7
1 -0.68262258  0.3425211 -0.1165502 ⋯ -0.5877486 -1.2641239 -1.32380742
2  0.26136061 -0.3839292 -0.5273679 ⋯ -0.1426103 -0.8564434  0.06464883
3 -1.26412388  0.3425211 -0.0387720 ⋯ -0.0387720 -1.0610663 -1.53938088
4  0.01292112  0.0387720  0.9743216 ⋯ -1.0610663  0.2480138 -0.27475411
5 -0.19504103  1.2086323  1.2641239 ⋯ -0.8564434 -0.0387720  0.46885224
6  0.85644338  0.1818887  2.0411380 ⋯ -0.2881971 -1.1566322  1.06106625
  IGF1R      FKBP5     H2AFJ      PRKCB       PDE3B      LINC01619   ADIPOR2
1 -0.1165502 -2.314897 -0.7156187  0.19504103 -0.4688522  0.44019785  0.6826226
2  0.4119005 -0.195041 -0.6187479  0.32885136  0.5573042  0.06464883 -0.2747541
3 -0.4688522 -1.208632 -1.5393809 -0.66640129 -1.3238074 -0.66640129 -0.4978969
4  0.0387720 -1.867329 -1.3238074 -0.23471108 -0.8943512  0.06464883  1.0167374
5 -0.4401979 -2.041138 -0.4978969 -0.32885136 -0.6826226  0.89435119  0.4688522
6 -0.6503535 -1.459855  0.6503535 -0.09056902 -1.6300412  0.27475411 -0.8197281

In [17]:
top_500_factor3_genes_matrix$sample_id = rownames(top_500_factor3_genes_matrix)

In [18]:
#write.csv(top_500_factor3_genes_matrix,"/ictstr01/home/icb/bhavishya.nelakuditi/mofa_workflow/scripts/making_proxy/top_500_factor3_genes_matrix.csv", row.names = FALSE)

In [19]:
head(top_500_factor3_genes_matrix)

  NLRP3      AP1S2      LINC01588 PNRC1      SERPINB9   SEPTIN4.AS1 IL1B
1 0.49789692  0.2214497 0.5273679 -0.4544784  1.3238074 0.6503535   0.44019785
2 0.61874786  0.7840859 0.6187479  0.7494131 -0.5877486 0.7840859   0.19504103
3 0.22144974 -0.3016924 0.3839292  0.8752401  1.1566322 0.8197281   0.01292112
4 0.09056902 -0.6503535 0.7156187 -0.6344714  0.9743216 0.6187479   0.06464883
5 1.32380742  0.2480138 1.4598551  1.2641239  0.2747541 0.4688522   1.06106625
6 1.73650701  0.2747541 2.3148972  1.0386467  2.0411380 2.0411380   1.73650701
  NFKBIZ      FTH1       FLNA       ⋯ ASH1L      SMG7        IGF1R
1 -0.68262258  0.3425211 -0.1165502 ⋯ -1.2641239 -1.32380742 -0.1165502
2  0.26136061 -0.3839292 -0.5273679 ⋯ -0.8564434  0.06464883  0.4119005
3 -1.26412388  0.3425211 -0.0387720 ⋯ -1.0610663 -1.53938088 -0.4688522
4  0.01292112  0.0387720  0.9743216 ⋯  0.2480138 -0.27475411  0.0387720
5 -0.19504103  1.2086323  1.2641239 ⋯ -0.0387720  0.46885224 -0.4401979
6  0.85644338  0.1818887  2.0411380 ⋯ -1.1566322  1.06106625 -0.6503535
  FKBP5     H2AFJ      PRKCB       PDE3B      LINC01619   ADIPOR2    sample_id
1 -2.314897 -0.7156187  0.19504103 -0.4688522  0.44019785  0.6826226 1
2 -0.195041 -0.6187479  0.32885136  0.5573042  0.06464883 -0.2747541 2
3 -1.208632 -1.5393809 -0.66640129 -1.3238074 -0.66640129 -0.4978969 3
4 -1.867329 -1.3238074 -0.23471108 -0.8943512  0.06464883  1.0167374 4
5 -2.041138 -0.4978969 -0.32885136 -0.6826226  0.89435119  0.4688522 5
6 -1.459855  0.6503535 -0.09056902 -1.6300412  0.27475411 -0.8197281 6